window.HAUNTED_STOPS = [
  {
    "id": "H-001",
    "title": "Sauer Castle",
    "city": "Kansas City",
    "state": "KS",
    "lat": 39.06891,
    "lon": -94.63361,
    "cluster": "Kansas City launch",
    "siteType": "Private historic mansion",
    "phenomenon": "Long-running reports describe lights in the tower and figures at windows when the house appeared unoccupied.",
    "evidence": "B - Established regional folklore",
    "detourMiles": "12",
    "priority": "Strong",
    "visit": "Exterior daylight photo stop",
    "access": "Private property. View only from a legal public location and do not enter the grounds.",
    "official": "https://www.visitkc.com/articles/kansas-citys-real-haunted-houses/",
    "folklore": "https://www.visitkc.com/articles/kansas-citys-real-haunted-houses/"
  },
  {
    "id": "H-002",
    "title": "John Wornall House Museum",
    "city": "Kansas City",
    "state": "MO",
    "lat": 39.01684,
    "lon": -94.59248,
    "cluster": "Kansas City launch",
    "siteType": "Historic house museum",
    "phenomenon": "Visitors and staff have described pipe-tobacco smells, figures in windows, and soldier-like apparitions connected to the house's Civil War field-hospital history.",
    "evidence": "A - Institution acknowledges folklore",
    "detourMiles": "8",
    "priority": "Must",
    "visit": "Museum tour or scheduled evening event",
    "access": "Tour during posted museum hours. Evening and paranormal programming is event-specific.",
    "official": "https://wornallmajors.org/",
    "folklore": "https://www.visitkc.com/articles/kansas-citys-real-haunted-houses/"
  },
  {
    "id": "H-003",
    "title": "Alexander Majors House Museum",
    "city": "Kansas City",
    "state": "MO",
    "lat": 38.97969,
    "lon": -94.60782,
    "cluster": "Kansas City launch",
    "siteType": "Historic house museum",
    "phenomenon": "The house promotes stories of a longtime caretaker and other lingering presences, and it hosts organized paranormal investigations.",
    "evidence": "A - Formal paranormal programming",
    "detourMiles": "7",
    "priority": "Must",
    "visit": "Paranormal night or museum tour",
    "access": "Seasonal museum schedule. Book special investigations in advance.",
    "official": "https://wornallmajors.org/explore/majors-house/",
    "folklore": "https://wornallmajors.org/events/paranormal-night-at-the-alexander-majors-house-museum/"
  },
  {
    "id": "H-004",
    "title": "Vaile Mansion",
    "city": "Independence",
    "state": "MO",
    "lat": 39.10227,
    "lon": -94.41463,
    "cluster": "Kansas City launch",
    "siteType": "Historic mansion museum",
    "phenomenon": "Regional folklore centers on a former resident whose figure is said to appear in rooms and upper windows.",
    "evidence": "B - Established regional folklore",
    "detourMiles": "8",
    "priority": "Strong",
    "visit": "Guided historic tour",
    "access": "Enter only during posted tour hours. The grounds may have separate seasonal rules.",
    "official": "https://www.vailemansion.org/",
    "folklore": "https://www.visitkc.com/articles/kansas-citys-real-haunted-houses/"
  },
  {
    "id": "H-005",
    "title": "Belvoir Winery and Inn",
    "city": "Liberty",
    "state": "MO",
    "lat": 39.22869,
    "lon": -94.4072,
    "cluster": "Kansas City launch",
    "siteType": "Historic complex, winery and inn",
    "phenomenon": "Guests and investigators have reported footsteps, voices, shadowy movement, and activity in buildings from the former Odd Fellows complex.",
    "evidence": "B - Established regional folklore",
    "detourMiles": "8",
    "priority": "Strong",
    "visit": "Public tasting-room visit or overnight stay",
    "access": "Operating business. Stay within guest and public areas; some buildings may be closed.",
    "official": "https://www.belvoirwinery.com/",
    "folklore": "https://missouriwine.org/news/belvoir-winery-a-hauntingly-good-time"
  },
  {
    "id": "H-006",
    "title": "The Elms Hotel and Spa",
    "city": "Excelsior Springs",
    "state": "MO",
    "lat": 39.33966,
    "lon": -94.22665,
    "cluster": "Kansas City launch",
    "siteType": "Historic operating hotel",
    "phenomenon": "Friendly resident spirits are part of the hotel's lore, including reports associated with the pool area and a woman in period housekeeping attire.",
    "evidence": "A - Hotel offers ghost experiences",
    "detourMiles": "25",
    "priority": "Optional",
    "visit": "Ghost tour or overnight",
    "access": "This is the largest Missouri-side detour. Reserve tours or lodging and respect guest-only areas.",
    "official": "https://www.elmshotelandspa.com/",
    "folklore": "https://www.visitkc.com/articles/kansas-citys-real-haunted-houses/"
  },
  {
    "id": "H-007",
    "title": "The Tiger Hotel",
    "city": "Columbia",
    "state": "MO",
    "lat": 38.95153,
    "lon": -92.33411,
    "cluster": "Central Missouri",
    "siteType": "Historic operating hotel",
    "phenomenon": "Local accounts mention unexplained sounds and a lingering presence in the historic downtown hotel, but documentation is lighter than at the route's major haunted venues.",
    "evidence": "C - Local legend",
    "detourMiles": "1",
    "priority": "Optional",
    "visit": "Lobby, meal, or overnight",
    "access": "Operating hotel. Public spaces and booked guest areas only.",
    "official": "https://www.thetigerhotel.com/",
    "folklore": "https://www.hauntedplaces.org/item/tiger-hotel/"
  },
  {
    "id": "H-008",
    "title": "Missouri State Penitentiary",
    "city": "Jefferson City",
    "state": "MO",
    "lat": 38.5734,
    "lon": -92.1606,
    "cluster": "Jefferson City",
    "siteType": "Decommissioned prison museum",
    "phenomenon": "Official tours describe voices, footsteps, shadows, and unexplained activity throughout the cellblocks and older buildings.",
    "evidence": "A - Formal paranormal programming",
    "detourMiles": "18",
    "priority": "Must",
    "visit": "Two-hour ghost tour",
    "access": "Ticketed entry. Age restrictions apply to ghost hunts and overnight investigations. Choose the historical ghost tour for the least intense experience.",
    "official": "https://missouripentours.com/ghost-paranormal-tours/",
    "folklore": "https://missouripentours.com/ghost-paranormal-tours/"
  },
  {
    "id": "H-009",
    "title": "Missouri Governor's Mansion",
    "city": "Jefferson City",
    "state": "MO",
    "lat": 38.57614,
    "lon": -92.16939,
    "cluster": "Jefferson City",
    "siteType": "Historic government residence",
    "phenomenon": "Stories passed through staff and visitors include footsteps, doors or objects moving, and a woman-like presence in the nineteenth-century residence.",
    "evidence": "B - Long-running local folklore",
    "detourMiles": "0.7",
    "priority": "Strong",
    "visit": "Reserved daytime tour",
    "access": "Security-controlled government property. Tours can require advance reservations and may be unavailable during official use.",
    "official": "https://mansion.mo.gov/",
    "folklore": "https://www.legendsofamerica.com/mo-governorsmansion/"
  },
  {
    "id": "H-010",
    "title": "Zombie Road, official Rock Hollow Trail",
    "city": "Wildwood",
    "state": "MO",
    "lat": 38.57731,
    "lon": -90.66036,
    "cluster": "St. Louis approach",
    "siteType": "Wooded public trail with urban legend",
    "phenomenon": "The old rail corridor is associated with stories of phantom lights, shadow figures, distant voices, and a feeling of being followed.",
    "evidence": "B - Famous regional legend",
    "detourMiles": "18",
    "priority": "Strong",
    "visit": "Late-afternoon walk before closing",
    "access": "Use only the official Rock Hollow Trail. Daily hours are 5 a.m. to 10 p.m. Do not enter closed rail property or remain after hours.",
    "official": "https://www.cityofwildwood.com/facilities/facility/details/Rock-Hollow-Trail-29",
    "folklore": "https://www.legendsofamerica.com/mo-zombieroad/"
  },
  {
    "id": "H-011",
    "title": "Lemp Mansion",
    "city": "St. Louis",
    "state": "MO",
    "lat": 38.59317,
    "lon": -90.21581,
    "cluster": "St. Louis and Alton",
    "siteType": "Historic mansion, restaurant and inn",
    "phenomenon": "One of the region's best-known haunted houses, with reports of footsteps, voices, cold areas, apparitions, and activity in rooms tied to the Lemp family.",
    "evidence": "A - Venue embraces haunting and tours",
    "detourMiles": "3",
    "priority": "Must",
    "visit": "Dinner, history tour, or overnight",
    "access": "Operating restaurant and inn. Reserve tours or rooms and stay out of private areas.",
    "official": "https://www.lempmansion.com/",
    "folklore": "https://www.lempmansion.com/haunted-history/"
  },
  {
    "id": "H-012",
    "title": "Campbell House Museum",
    "city": "St. Louis",
    "state": "MO",
    "lat": 38.63137,
    "lon": -90.20181,
    "cluster": "St. Louis and Alton",
    "siteType": "Historic house museum",
    "phenomenon": "Local accounts describe footsteps, displaced objects, cold spots, and a formal Victorian interior that can feel occupied when rooms are empty.",
    "evidence": "B - Established local folklore",
    "detourMiles": "2",
    "priority": "Strong",
    "visit": "Guided museum tour",
    "access": "Visit during museum hours or a scheduled special program.",
    "official": "https://www.campbellhousemuseum.org/",
    "folklore": "https://www.stlouisghosts.com/haunted-places/campbell-house-museum/"
  },
  {
    "id": "H-013",
    "title": "Fabulous Fox Theatre",
    "city": "St. Louis",
    "state": "MO",
    "lat": 38.63911,
    "lon": -90.23135,
    "cluster": "St. Louis and Alton",
    "siteType": "Historic operating theatre",
    "phenomenon": "Theatre lore includes unexplained footsteps, voices, seat movement, and figures seen in backstage or balcony areas.",
    "evidence": "B - Established theatre folklore",
    "detourMiles": "4",
    "priority": "Strong",
    "visit": "Public theatre tour or performance",
    "access": "Backstage access is limited to tours and events. Check the current tour calendar.",
    "official": "https://www.fabulousfox.com/",
    "folklore": "https://www.stlouisghosts.com/haunted-places/fabulous-fox-theatre/"
  },
  {
    "id": "H-014",
    "title": "McPike Mansion",
    "city": "Alton",
    "state": "IL",
    "lat": 38.90237,
    "lon": -90.18469,
    "cluster": "St. Louis and Alton",
    "siteType": "Restoration-stage historic mansion",
    "phenomenon": "Investigators and tour guests report apparitions, voices, touches, and activity in the cellar and former living areas.",
    "evidence": "A - Paranormal tours and investigations",
    "detourMiles": "20",
    "priority": "Must",
    "visit": "Scheduled history or paranormal tour",
    "access": "Active restoration site. Entry is by scheduled event or permission only.",
    "official": "https://www.mcpikemansion.com/",
    "folklore": "https://www.mcpikemansion.com/"
  },
  {
    "id": "H-015",
    "title": "Mineral Springs Hotel Building",
    "city": "Alton",
    "state": "IL",
    "lat": 38.89108,
    "lon": -90.18109,
    "cluster": "St. Louis and Alton",
    "siteType": "Historic commercial building and former hotel",
    "phenomenon": "The building is associated with reports of voices, figures, splashing sounds, and activity around its former pool and hotel spaces.",
    "evidence": "B - Major Alton ghost-tour site",
    "detourMiles": "1",
    "priority": "Strong",
    "visit": "Booked Alton history or ghost tour",
    "access": "Tenants and access arrangements change. Do not assume unrestricted entry; book through a current operator.",
    "official": "https://www.altonhauntings.com/",
    "folklore": "https://www.altonhauntings.com/mineral-springs-hotel/"
  },
  {
    "id": "H-016",
    "title": "Inn at 835",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.79315,
    "lon": -89.65076,
    "cluster": "Springfield",
    "siteType": "Historic operating inn",
    "phenomenon": "Guests have described perfume-like scents, footsteps, doors behaving oddly, and a woman's presence linked by folklore to the original owner.",
    "evidence": "B - Established inn folklore",
    "detourMiles": "2",
    "priority": "Strong",
    "visit": "Overnight stay",
    "access": "Operating lodging. Public and guest spaces only.",
    "official": "https://www.innat835.com/",
    "folklore": "https://www.hauntedrooms.com/illinois/haunted-places/haunted-hotels/inn-at-835-springfield"
  },
  {
    "id": "H-017",
    "title": "Dana-Thomas House",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.79461,
    "lon": -89.6502,
    "cluster": "Springfield",
    "siteType": "Frank Lloyd Wright historic house",
    "phenomenon": "Guides and visitors have circulated stories of unexplained footsteps, sounds, and a presence in the richly detailed house.",
    "evidence": "C - Local legend",
    "detourMiles": "0.4",
    "priority": "Strong",
    "visit": "Daytime architectural tour",
    "access": "Guided entry only. Historic stairs and narrow areas may affect accessibility.",
    "official": "https://dnrhistoric.illinois.gov/experience/sites/site.dana-thomas-house.html",
    "folklore": "https://www.hauntedplaces.org/item/dana-thomas-house/"
  },
  {
    "id": "H-018",
    "title": "Lincoln Tomb and Oak Ridge Cemetery",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.82028,
    "lon": -89.67566,
    "cluster": "Springfield",
    "siteType": "Historic tomb and cemetery",
    "phenomenon": "Springfield ghost lore includes unexplained sounds and sensed presences near historic graves, while the tomb itself provides a solemn, atmospheric stop.",
    "evidence": "C - Local folklore and atmosphere",
    "detourMiles": "3",
    "priority": "Strong",
    "visit": "Respectful daylight visit",
    "access": "Follow cemetery and historic-site hours. No nighttime wandering or intrusive investigation.",
    "official": "https://dnrhistoric.illinois.gov/experience/sites/site.lincoln-tomb.html",
    "folklore": "https://springfieldwalks.com/"
  },
  {
    "id": "H-019",
    "title": "Old Joliet Prison",
    "city": "Joliet",
    "state": "IL",
    "lat": 41.54856,
    "lon": -88.07396,
    "cluster": "Joliet and Chicago outskirts",
    "siteType": "Historic decommissioned prison",
    "phenomenon": "Visitors report footsteps, voices, shadows, and a heavy atmosphere in the cell houses and administrative buildings.",
    "evidence": "A - Historic tours plus paranormal reputation",
    "detourMiles": "2",
    "priority": "Must",
    "visit": "Historic guided or self-guided tour",
    "access": "Seasonal ticketed site, generally spring through fall. This recommendation is the historic prison, not a staged Halloween attraction.",
    "official": "https://www.jolietprison.org/tours.html",
    "folklore": "https://www.wbez.org/culture-the-arts/2018/10/26/is-the-old-joliet-prison-haunted"
  },
  {
    "id": "H-020",
    "title": "Rialto Square Theatre",
    "city": "Joliet",
    "state": "IL",
    "lat": 41.52694,
    "lon": -88.08166,
    "cluster": "Joliet and Chicago outskirts",
    "siteType": "Historic operating theatre",
    "phenomenon": "Theatre stories include a young figure, phantom movement, and unexplained sounds in backstage and balcony areas.",
    "evidence": "B - Long-running theatre folklore",
    "detourMiles": "2",
    "priority": "Strong",
    "visit": "Performance, architecture tour, or special event",
    "access": "Public access depends on shows and scheduled tours. Backstage areas are restricted.",
    "official": "https://rialtosquare.com/",
    "folklore": "https://www.hauntedplaces.org/item/rialto-square-theatre/"
  },
  {
    "id": "H-021",
    "title": "Bachelor's Grove Cemetery",
    "city": "Midlothian",
    "state": "IL",
    "lat": 41.6309,
    "lon": -87.7709,
    "cluster": "Joliet and Chicago outskirts",
    "siteType": "Small historic cemetery in forest preserve",
    "phenomenon": "A famous Chicago-area legend involving phantom vehicles, lights, figures, and a woman sometimes reported near the graves.",
    "evidence": "B - Famous regional folklore",
    "detourMiles": "14",
    "priority": "Optional",
    "visit": "Quiet daylight walk only",
    "access": "Use legal forest-preserve parking and trails. Respect graves, posted hours, and all closure signs. Do not visit after dark.",
    "official": "https://fpdcc.com/places/locations/rubio-woods/",
    "folklore": "https://www.bachelorsgrove.com/"
  },
  {
    "id": "H-022",
    "title": "Resurrection Cemetery, Resurrection Mary legend",
    "city": "Justice",
    "state": "IL",
    "lat": 41.75552,
    "lon": -87.83877,
    "cluster": "Joliet and Chicago outskirts",
    "siteType": "Operating cemetery and roadside legend",
    "phenomenon": "For decades, drivers have reported a young woman in pale clothing along Archer Avenue who vanishes near the cemetery gates.",
    "evidence": "B - Classic Chicago-area legend",
    "detourMiles": "12",
    "priority": "Optional",
    "visit": "Daylight cemetery visit or legal drive-by",
    "access": "Active sacred cemetery. Visit only during posted hours, do not block roads, and do not approach strangers or stage roadside encounters.",
    "official": "https://www.catholiccemeterieschicago.org/Locations/Details/Resurrection",
    "folklore": "https://www.chicagohistory.org/resurrection-mary/"
  },
  {
    "id": "H-023",
    "title": "Old Lake County Jail",
    "city": "Crown Point",
    "state": "IN",
    "lat": 41.41657,
    "lon": -87.36556,
    "cluster": "Northwest Indiana",
    "siteType": "Historic jail museum",
    "phenomenon": "The jail's tours describe footsteps, voices, cold areas, and unexplained motion inside the cellblocks and former living quarters.",
    "evidence": "A - Current ghost tours",
    "detourMiles": "7",
    "priority": "Must",
    "visit": "Scheduled ghost or history tour",
    "access": "Entry is by tour or event. Check age guidance and current dates.",
    "official": "https://www.southshorecva.com/listing/old-lake-county-jail/247/",
    "folklore": "https://www.southshorecva.com/blog/post/haunted-old-lake-county-jail/"
  },
  {
    "id": "H-024",
    "title": "Diana of the Dunes Dare, West Beach",
    "city": "Gary",
    "state": "IN",
    "lat": 41.62235,
    "lon": -87.2073,
    "cluster": "Indiana Dunes",
    "siteType": "National park dune trail and ghost legend",
    "phenomenon": "The National Park Service retells the legend of Alice Mabel Gray, Diana of the Dunes, whose solitary life inspired later ghost stories in the dunes.",
    "evidence": "A - NPS acknowledges the ghost story",
    "detourMiles": "3",
    "priority": "Must",
    "visit": "Sunset hike while the park is open",
    "access": "Park fees and seasonal parking controls may apply. Stay on marked trails and confirm closing time before a sunset visit.",
    "official": "https://www.nps.gov/thingstodo/dianadunesdare.htm",
    "folklore": "https://www.nps.gov/thingstodo/dianadunesdare.htm"
  },
  {
    "id": "H-025",
    "title": "Barker Mansion",
    "city": "Michigan City",
    "state": "IN",
    "lat": 41.71466,
    "lon": -86.90008,
    "cluster": "Michigan City",
    "siteType": "Historic mansion museum",
    "phenomenon": "Local reports describe footsteps, voices, and movement in rooms associated with the Barker family and household staff.",
    "evidence": "B - Established local folklore",
    "detourMiles": "3",
    "priority": "Strong",
    "visit": "Guided mansion tour",
    "access": "Tour availability varies by season and restoration work.",
    "official": "https://www.barkermansion.com/",
    "folklore": "https://www.hauntedplaces.org/item/barker-mansion/"
  },
  {
    "id": "H-026",
    "title": "Old Lighthouse Museum",
    "city": "Michigan City",
    "state": "IN",
    "lat": 41.72184,
    "lon": -86.90548,
    "cluster": "Michigan City",
    "siteType": "Historic lighthouse museum",
    "phenomenon": "Paranormal programs and local accounts cite footsteps, voices, and a keeper-like presence in the lighthouse residence.",
    "evidence": "A - Hosted paranormal investigations",
    "detourMiles": "2",
    "priority": "Must",
    "visit": "Museum tour or scheduled investigation",
    "access": "Seasonal museum. Check stairs, tour hours, and special-event rules.",
    "official": "https://michigancitylighthousemuseum.com/",
    "folklore": "https://michigancitylighthousemuseum.com/events/"
  },
  {
    "id": "H-027",
    "title": "Washington Hall, University of Notre Dame",
    "city": "Notre Dame",
    "state": "IN",
    "lat": 41.70331,
    "lon": -86.23952,
    "cluster": "South Bend",
    "siteType": "Historic campus theatre",
    "phenomenon": "Notre Dame sources preserve a century-old campus legend involving footsteps, sounds, and a figure associated by tradition with George Gipp.",
    "evidence": "A - University preserves the folklore",
    "detourMiles": "3",
    "priority": "Must",
    "visit": "Exterior campus stop or public event",
    "access": "Campus access is generally possible, but interior access depends on events and university rules.",
    "official": "https://washingtonhall.nd.edu/about-washington-hall/",
    "folklore": "https://al.nd.edu/news/latest-news/a-history-of-washington-halland-of-notre-dame/"
  },
  {
    "id": "H-028",
    "title": "Tippecanoe Place",
    "city": "South Bend",
    "state": "IN",
    "lat": 41.6758,
    "lon": -86.25787,
    "cluster": "South Bend",
    "siteType": "Historic mansion restaurant",
    "phenomenon": "Staff and guest stories include footsteps, voices, a woman's figure, and movement in less-used parts of the former Studebaker mansion.",
    "evidence": "B - Established local folklore",
    "detourMiles": "1",
    "priority": "Strong",
    "visit": "Meal or public historic space",
    "access": "Operating restaurant and event venue. Private rooms and upper areas may be restricted.",
    "official": "https://www.tippe.com/",
    "folklore": "https://www.visitsouthbend.com/blog/strange-things-in-south-bend-mishawaka/"
  },
  {
    "id": "H-029",
    "title": "Morris Performing Arts Center",
    "city": "South Bend",
    "state": "IN",
    "lat": 41.67794,
    "lon": -86.25064,
    "cluster": "South Bend",
    "siteType": "Historic operating theatre",
    "phenomenon": "The venue's own ghost tours describe mysterious footsteps, lights, taps, and activity in the basement, stage wings, and former tunnel areas.",
    "evidence": "A - Official ghost tours",
    "detourMiles": "1",
    "priority": "Must",
    "visit": "Ghost tour when scheduled, otherwise theatre tour",
    "access": "Regular tours are available by arrangement. Ghost tours are typically seasonal, so verify the 2026 calendar.",
    "official": "https://morriscenter.org/plan-your-visit/tours/",
    "folklore": "https://morriscenter.org/event/ghost-tours/2025-09-19/1/"
  },
  {
    "id": "H-030",
    "title": "Henderson Castle",
    "city": "Kalamazoo",
    "state": "MI",
    "lat": 42.29251,
    "lon": -85.59446,
    "cluster": "Kalamazoo",
    "siteType": "Historic operating inn and event venue",
    "phenomenon": "Guests and investigators report apparitions, voices, footsteps, and activity in guest rooms and former family areas.",
    "evidence": "B - Widely reported hotel folklore",
    "detourMiles": "3",
    "priority": "Must",
    "visit": "Tour, meal, or overnight",
    "access": "Operating inn and event venue. Reserve ahead and respect guest privacy.",
    "official": "https://www.hendersoncastle.com/",
    "folklore": "https://www.mlive.com/news/kalamazoo/2019/10/is-henderson-castle-haunted.html"
  },
  {
    "id": "H-031",
    "title": "Kalamazoo State Theatre",
    "city": "Kalamazoo",
    "state": "MI",
    "lat": 42.28798,
    "lon": -85.58286,
    "cluster": "Kalamazoo",
    "siteType": "Historic operating theatre",
    "phenomenon": "Local accounts describe a stage statue that appears to shift, voices, music, and other sounds heard when the building is quiet.",
    "evidence": "C - Local legend",
    "detourMiles": "1",
    "priority": "Strong",
    "visit": "Performance or authorized tour",
    "access": "Interior access is event-dependent. Do not attempt backstage access without permission.",
    "official": "https://kalamazoostate.com/",
    "folklore": "https://www.michiganhauntedhouses.com/real-haunt/kalamazoo-state-theatre.html"
  },
  {
    "id": "H-032",
    "title": "The English Inn",
    "city": "Eaton Rapids",
    "state": "MI",
    "lat": 42.55602,
    "lon": -84.65755,
    "cluster": "Lansing approach",
    "siteType": "Historic operating inn and restaurant",
    "phenomenon": "Regional stories describe footsteps, objects moving, and a woman-like presence in the manor and guest areas.",
    "evidence": "C - Local inn folklore",
    "detourMiles": "8",
    "priority": "Optional",
    "visit": "Meal or overnight",
    "access": "Operating hospitality property. Public and booked guest areas only.",
    "official": "https://www.englishinn.com/directions",
    "folklore": "https://www.hauntedplaces.org/item/the-english-inn/"
  },
  {
    "id": "H-033",
    "title": "Turner-Dodge House",
    "city": "Lansing",
    "state": "MI",
    "lat": 42.75087,
    "lon": -84.54827,
    "cluster": "Lansing",
    "siteType": "City-owned historic house",
    "phenomenon": "The mansion is a recurring Lansing ghost-tour stop, with stories of footsteps, sounds, and sensed presences in upper rooms.",
    "evidence": "B - Included in local ghost programming",
    "detourMiles": "2",
    "priority": "Strong",
    "visit": "Historic tour or scheduled event",
    "access": "City facility. Interior access is limited to tours, rentals, and public events.",
    "official": "https://www.lansingmi.gov/461/Turner-Dodge-House",
    "folklore": "https://www.michigan.org/property/lansing-ghost-tour-lawless-legends-and-laments-lanternlight"
  },
  {
    "id": "H-034",
    "title": "Michigan State Capitol",
    "city": "Lansing",
    "state": "MI",
    "lat": 42.73364,
    "lon": -84.55533,
    "cluster": "Lansing",
    "siteType": "Historic government building",
    "phenomenon": "Lansing ghost tours repeat reports of strange sounds and lingering presences after hours in the Victorian-era Capitol.",
    "evidence": "B - Recognized local ghost-tour stop",
    "detourMiles": "1",
    "priority": "Strong",
    "visit": "Free daytime tour",
    "access": "Security screening applies. Public hours are generally weekdays and the first Saturday of each month; verify current schedule.",
    "official": "https://capitol.michigan.gov/tours",
    "folklore": "https://www.michigan.org/property/lansing-ghost-tour-lawless-legends-and-laments-lanternlight"
  },
  {
    "id": "H-035",
    "title": "Pere Cheney Ghost Town and Cemetery",
    "city": "Grayling area",
    "state": "MI",
    "lat": 44.5731,
    "lon": -84.6364,
    "cluster": "Grayling",
    "siteType": "Abandoned settlement site and cemetery",
    "phenomenon": "The vanished logging settlement has accumulated stories of phantom voices, lights, and a mysterious woman, layered over the real history of a town lost to disease and economic decline.",
    "evidence": "B - Famous northern Michigan legend",
    "detourMiles": "8",
    "priority": "Must",
    "visit": "Daylight historical stop",
    "access": "Use public roads and marked access only. Roads can be sandy or muddy. Do not enter private parcels, disturb graves, or remain after dark.",
    "official": "https://www.michigan.gov/libraryofmichigan/public/michigan/county-guides/guides/crawford",
    "folklore": "https://www.michiganpublic.org/offbeat/2017-07-12/how-did-pere-cheney-become-a-ghost-town"
  },
  {
    "id": "H-036",
    "title": "Colonial Michilimackinac",
    "city": "Mackinaw City",
    "state": "MI",
    "lat": 45.78657,
    "lon": -84.72717,
    "cluster": "Straits of Mackinac",
    "siteType": "Reconstructed eighteenth-century fort",
    "phenomenon": "The fort's long military and trading history has produced stories of footsteps, voices, and figures in reconstructed buildings, especially during quiet hours.",
    "evidence": "B - Historic-site folklore",
    "detourMiles": "0",
    "priority": "Must",
    "visit": "Daytime fort tour",
    "access": "Seasonal ticketed attraction. Special spooky programs can be more theatrical than the rest of this list, so choose the regular history visit.",
    "official": "https://www.mackinacparks.com/attraction/colonial-michilimackinac/",
    "folklore": "https://www.mackinacparks.com/event/fort-fright/"
  },
  {
    "id": "H-037",
    "title": "Old Mackinac Point Lighthouse",
    "city": "Mackinaw City",
    "state": "MI",
    "lat": 45.78864,
    "lon": -84.73255,
    "cluster": "Straits of Mackinac",
    "siteType": "Historic lighthouse museum",
    "phenomenon": "Keeper-era stories, shipwreck history, wind, fog signals, and isolated rooms make this a strong atmospheric lighthouse stop, with occasional local ghost reports.",
    "evidence": "C - Lighthouse folklore and atmosphere",
    "detourMiles": "0.5",
    "priority": "Must",
    "visit": "Lighthouse and tower tour",
    "access": "Seasonal hours. Tower access involves stairs and may be weather-dependent.",
    "official": "https://www.mackinacparks.com/attraction/old-mackinac-point-lighthouse/",
    "folklore": "https://www.mackinacparks.com/attraction/old-mackinac-point-lighthouse/"
  },
  {
    "id": "H-038",
    "title": "Cheboygan Opera House",
    "city": "Cheboygan",
    "state": "MI",
    "lat": 45.64619,
    "lon": -84.47457,
    "cluster": "Cheboygan ferry staging",
    "siteType": "Historic operating theatre",
    "phenomenon": "The venue's own history materials reference ghosts and unexplained stories alongside its long vaudeville and civic history.",
    "evidence": "A - Venue acknowledges ghost lore",
    "detourMiles": "1",
    "priority": "Strong",
    "visit": "Performance or authorized tour",
    "access": "Interior access depends on performances and events. This is close to the Bois Blanc ferry staging area.",
    "official": "https://theoperahouse.org/",
    "folklore": "https://theoperahouse.org/book/"
  },
  {
    "id": "H-039",
    "title": "Mission Point Resort",
    "city": "Mackinac Island",
    "state": "MI",
    "lat": 45.84921,
    "lon": -84.60356,
    "cluster": "Optional Mackinac Island branch",
    "siteType": "Operating island resort",
    "phenomenon": "The resort has a long reputation for a young man's apparition and unexplained activity around its theatre and older college-era spaces.",
    "evidence": "B - Widely reported resort folklore",
    "detourMiles": "0",
    "priority": "Optional",
    "visit": "Separate Mackinac Island overnight or day trip",
    "access": "Not on the Bois Blanc ferry route. This requires a separate passenger ferry from Mackinaw City or St. Ignace and several hours of added logistics.",
    "official": "https://www.missionpoint.com/our-resort",
    "folklore": "https://www.audacy.com/wwjnewsradio/news/local/mission-point-resort-on-mackinac-island-has-a-famous-ghost"
  },
  {
    "id": "H-040",
    "title": "Bois Blanc Island Lighthouse",
    "city": "Bois Blanc Island",
    "state": "MI",
    "lat": 45.81,
    "lon": -84.42,
    "cluster": "Bois Blanc Island destination",
    "siteType": "Deactivated historic lighthouse, private residence",
    "phenomenon": "This is primarily an isolated and atmospheric maritime site rather than a strongly documented haunting. Its history includes storms, lost earlier towers, keeper life, and long periods of remoteness.",
    "evidence": "D - Atmospheric, limited haunting claims",
    "detourMiles": "17",
    "priority": "Destination",
    "visit": "View from public water or legal public vantage",
    "access": "The historic lighthouse is privately owned. Do not enter or approach private property. Island roads are mostly unpaved and conditions vary.",
    "official": "https://www.history.uscg.mil/Browse-by-Topic/Assets/Land/Lighthouses-Light-Stations/Article/1900384/bois-blanc-island-light/",
    "folklore": "https://www.us-lighthouses.com/bois-blanc-island-lighthouse"
  }
];
