window.HAUNTED_STOPS = [
  {
    "id": "H-001",
    "title": "Sauer Castle",
    "city": "Kansas City",
    "state": "KS",
    "lat": 39.06891,
    "lon": -94.63361,
    "cluster": "Kansas City launch",
    "siteType": "Private historic mansion",
    "phenomenon": "Long-running reports describe lights in the tower and figures at windows when the house appeared unoccupied.",
    "evidence": "B - Established regional folklore",
    "detourMiles": "12",
    "priority": "Strong",
    "visit": "Exterior daylight photo stop",
    "access": "Private property. View only from a legal public location and do not enter the grounds.",
    "official": "https://www.visitkc.com/articles/kansas-citys-real-haunted-houses/",
    "folklore": "https://www.visitkc.com/articles/kansas-citys-real-haunted-houses/",
    "history": "Anton Sauer, an Austrian immigrant who made his fortune in freight, built this Italianate villa above the Kaw River around 1871. Four generations of the family lived and died here, and the towered mansion has stood mostly empty for decades — which is exactly how a house earns a reputation. Generations of Kansas City kids have dared each other to drive past the tower at night."
  },
  {
    "id": "H-002",
    "title": "John Wornall House Museum",
    "city": "Kansas City",
    "state": "MO",
    "lat": 39.01684,
    "lon": -94.59248,
    "cluster": "Kansas City launch",
    "siteType": "Historic house museum",
    "phenomenon": "Visitors and staff have described pipe-tobacco smells, figures in windows, and soldier-like apparitions connected to the house's Civil War field-hospital history.",
    "evidence": "A - Institution acknowledges folklore",
    "detourMiles": "8",
    "priority": "Must",
    "visit": "Museum tour or scheduled evening event",
    "access": "Tour during posted museum hours. Evening and paranormal programming is event-specific.",
    "official": "https://wornallmajors.org/",
    "folklore": "https://www.visitkc.com/articles/kansas-citys-real-haunted-houses/",
    "history": "John Wornall built this Greek Revival farmhouse in 1858, and in October 1864 the Battle of Westport — the biggest Civil War battle west of the Mississippi — swept literally across his land. Both armies used the house as a field hospital, and soldiers died in its rooms. The pipe smoke and soldier figures people report tie straight back to those weeks."
  },
  {
    "id": "H-003",
    "title": "Alexander Majors House Museum",
    "city": "Kansas City",
    "state": "MO",
    "lat": 38.97969,
    "lon": -94.60782,
    "cluster": "Kansas City launch",
    "siteType": "Historic house museum",
    "phenomenon": "The house promotes stories of a longtime caretaker and other lingering presences, and it hosts organized paranormal investigations.",
    "evidence": "A - Formal paranormal programming",
    "detourMiles": "7",
    "priority": "Must",
    "visit": "Paranormal night or museum tour",
    "access": "Seasonal museum schedule. Book special investigations in advance.",
    "official": "https://wornallmajors.org/explore/majors-house/",
    "folklore": "https://wornallmajors.org/events/paranormal-night-at-the-alexander-majors-house-museum/",
    "history": "Alexander Majors was one of the founders of the Pony Express, and this 1856 house was his home base at the edge of the frontier. His great-granddaughter Louisa Johnston spent her last decades restoring the house nearly alone and died here in 1984 — staff say she never really clocked out, and the museum leans into it with organized paranormal nights."
  },
  {
    "id": "H-004",
    "title": "Vaile Mansion",
    "city": "Independence",
    "state": "MO",
    "lat": 39.10227,
    "lon": -94.41463,
    "cluster": "Kansas City launch",
    "siteType": "Historic mansion museum",
    "phenomenon": "Regional folklore centers on a former resident whose figure is said to appear in rooms and upper windows.",
    "evidence": "B - Established regional folklore",
    "detourMiles": "8",
    "priority": "Strong",
    "visit": "Guided historic tour",
    "access": "Enter only during posted tour hours. The grounds may have separate seasonal rules.",
    "official": "https://www.vailemansion.org/",
    "folklore": "https://www.visitkc.com/articles/kansas-citys-real-haunted-houses/",
    "history": "Colonel Harvey Vaile finished this 31-room Second Empire showpiece in 1881 — it was called one of the finest houses west of the Mississippi. His wife Sophia died in the house in 1883 during a federal mail-contract scandal that consumed the family, and the figure reported in the upper windows is usually said to be her."
  },
  {
    "id": "H-005",
    "title": "Belvoir Winery and Inn",
    "city": "Liberty",
    "state": "MO",
    "lat": 39.22869,
    "lon": -94.4072,
    "cluster": "Kansas City launch",
    "siteType": "Historic complex, winery and inn",
    "phenomenon": "Guests and investigators have reported footsteps, voices, shadowy movement, and activity in buildings from the former Odd Fellows complex.",
    "evidence": "B - Established regional folklore",
    "detourMiles": "8",
    "priority": "Strong",
    "visit": "Public tasting-room visit or overnight stay",
    "access": "Operating business. Stay within guest and public areas; some buildings may be closed.",
    "official": "https://www.belvoirwinery.com/",
    "folklore": "https://missouriwine.org/news/belvoir-winery-a-hauntingly-good-time",
    "history": "Belvoir began in the 1880s-1900s as the Odd Fellows Home District — a whole campus where the fraternal order housed its orphans, its elderly, and its sick, with its own hospital and cemetery. Hundreds of people lived out entire lives here. The winery and inn now occupy the old buildings, and they openly market the resident spirits rather than denying them."
  },
  {
    "id": "H-006",
    "title": "The Elms Hotel and Spa",
    "city": "Excelsior Springs",
    "state": "MO",
    "lat": 39.33966,
    "lon": -94.22665,
    "cluster": "Kansas City launch",
    "siteType": "Historic operating hotel",
    "phenomenon": "Friendly resident spirits are part of the hotel's lore, including reports associated with the pool area and a woman in period housekeeping attire.",
    "evidence": "A - Hotel offers ghost experiences",
    "detourMiles": "25",
    "priority": "Optional",
    "visit": "Ghost tour or overnight",
    "access": "This is the largest Missouri-side detour. Reserve tours or lodging and respect guest-only areas.",
    "official": "https://www.elmshotelandspa.com/",
    "folklore": "https://www.visitkc.com/articles/kansas-citys-real-haunted-houses/",
    "history": "The Elms has burned to the ground twice — the current 1912 hotel is the third on the site. In its heyday the mineral-springs resort drew gangsters (Al Capone reputedly gambled here) and, famously, Harry Truman, who spent election night 1948 asleep here while the papers wrongly declared he'd lost. Staff stories center on a 1920s-era gambler and a housekeeper who never left."
  },
  {
    "id": "H-007",
    "title": "The Tiger Hotel",
    "city": "Columbia",
    "state": "MO",
    "lat": 38.95153,
    "lon": -92.33411,
    "cluster": "Central Missouri",
    "siteType": "Historic operating hotel",
    "phenomenon": "Local accounts mention unexplained sounds and a lingering presence in the historic downtown hotel, but documentation is lighter than at the route's major haunted venues.",
    "evidence": "C - Local legend",
    "detourMiles": "1",
    "priority": "Optional",
    "visit": "Lobby, meal, or overnight",
    "access": "Operating hotel. Public spaces and booked guest areas only.",
    "official": "https://www.thetigerhotel.com/",
    "folklore": "https://www.hauntedplaces.org/item/tiger-hotel/",
    "history": "The Tiger opened in 1928 as Columbia's grand hotel — for decades the tallest building between St. Louis and Kansas City. It fell into decline, spent years as a retirement home, and was restored to a boutique hotel; the reports of phantom guests track the building's long, layered occupancy."
  },
  {
    "id": "H-008",
    "title": "Missouri State Penitentiary",
    "city": "Jefferson City",
    "state": "MO",
    "lat": 38.5734,
    "lon": -92.1606,
    "cluster": "Jefferson City",
    "siteType": "Decommissioned prison museum",
    "phenomenon": "Official tours describe voices, footsteps, shadows, and unexplained activity throughout the cellblocks and older buildings.",
    "evidence": "A - Formal paranormal programming",
    "detourMiles": "18",
    "priority": "Must",
    "visit": "Two-hour ghost tour",
    "access": "Ticketed entry. Age restrictions apply to ghost hunts and overnight investigations. Choose the historical ghost tour for the least intense experience.",
    "official": "https://missouripentours.com/ghost-paranormal-tours/",
    "folklore": "https://missouripentours.com/ghost-paranormal-tours/",
    "history": "Missouri State Penitentiary opened in 1836 — it was already housing prisoners when the Alamo fell — and ran continuously until 2004, making it one of the oldest prisons west of the Mississippi. Time magazine once called it 'the bloodiest 47 acres in America.' Sonny Liston boxed here as an inmate; James Earl Ray escaped from here in 1967, a year before he assassinated Dr. King. The tours go into the dungeon cells and the gas chamber."
  },
  {
    "id": "H-009",
    "title": "Missouri Governor's Mansion",
    "city": "Jefferson City",
    "state": "MO",
    "lat": 38.57614,
    "lon": -92.16939,
    "cluster": "Jefferson City",
    "siteType": "Historic government residence",
    "phenomenon": "Stories passed through staff and visitors include footsteps, doors or objects moving, and a woman-like presence in the nineteenth-century residence.",
    "evidence": "B - Long-running local folklore",
    "detourMiles": "0.7",
    "priority": "Strong",
    "visit": "Reserved daytime tour",
    "access": "Security-controlled government property. Tours can require advance reservations and may be unavailable during official use.",
    "official": "https://mansion.mo.gov/",
    "folklore": "https://www.legendsofamerica.com/mo-governorsmansion/",
    "history": "Missouri's governors have lived in this 1871 mansion ever since it was built. The best-known story belongs to Carrie Crittenden, the nine-year-old daughter of Governor Thomas Crittenden, who died of diphtheria in the house in 1882 — staff and residents have reported a child's laughter and footsteps for over a century."
  },
  {
    "id": "H-010",
    "title": "Zombie Road, official Rock Hollow Trail",
    "city": "Wildwood",
    "state": "MO",
    "lat": 38.57731,
    "lon": -90.66036,
    "cluster": "St. Louis approach",
    "siteType": "Wooded public trail with urban legend",
    "phenomenon": "The old rail corridor is associated with stories of phantom lights, shadow figures, distant voices, and a feeling of being followed.",
    "evidence": "B - Famous regional legend",
    "detourMiles": "18",
    "priority": "Strong",
    "visit": "Late-afternoon walk before closing",
    "access": "Use only the official Rock Hollow Trail. Daily hours are 5 a.m. to 10 p.m. Do not enter closed rail property or remain after hours.",
    "official": "https://www.cityofwildwood.com/facilities/facility/details/Rock-Hollow-Trail-29",
    "folklore": "https://www.legendsofamerica.com/mo-zombieroad/",
    "history": "Officially it's the Rock Hollow Trail, a paved path through Ozark woods — but for generations of St. Louis teenagers it was Zombie Road, an abandoned rail-and-quarry route with tales of shadow figures lining the tree line. The real history involves a 19th-century railroad, a vanished resort community by the Meramec River, and quarry accidents that seeded the legends."
  },
  {
    "id": "H-011",
    "title": "Lemp Mansion",
    "city": "St. Louis",
    "state": "MO",
    "lat": 38.59317,
    "lon": -90.21581,
    "cluster": "St. Louis and Alton",
    "siteType": "Historic mansion, restaurant and inn",
    "phenomenon": "One of the region's best-known haunted houses, with reports of footsteps, voices, cold areas, apparitions, and activity in rooms tied to the Lemp family.",
    "evidence": "A - Venue embraces haunting and tours",
    "detourMiles": "3",
    "priority": "Must",
    "visit": "Dinner, history tour, or overnight",
    "access": "Operating restaurant and inn. Reserve tours or rooms and stay out of private areas.",
    "official": "https://www.lempmansion.com/",
    "folklore": "https://www.lempmansion.com/haunted-history/",
    "history": "The Lemp family ran one of America's biggest breweries before Prohibition destroyed it — and the family with it. Four members, including three by their own hand inside this house, died across the early 1900s. The mansion is now a restaurant and inn that hosts murder-mystery dinners, and it's routinely ranked among the most haunted houses in America. A heavy story — the kind Elsie can decide how deep to go on."
  },
  {
    "id": "H-012",
    "title": "Campbell House Museum",
    "city": "St. Louis",
    "state": "MO",
    "lat": 38.63137,
    "lon": -90.20181,
    "cluster": "St. Louis and Alton",
    "siteType": "Historic house museum",
    "phenomenon": "Local accounts describe footsteps, displaced objects, cold spots, and a formal Victorian interior that can feel occupied when rooms are empty.",
    "evidence": "B - Established local folklore",
    "detourMiles": "2",
    "priority": "Strong",
    "visit": "Guided museum tour",
    "access": "Visit during museum hours or a scheduled special program.",
    "official": "https://www.campbellhousemuseum.org/",
    "folklore": "https://www.stlouisghosts.com/haunted-places/campbell-house-museum/",
    "history": "The Campbell House preserves the world of Robert Campbell, a fur-trade millionaire, almost untouched — the family kept nearly everything, so the 1880s interiors are real, not recreated. Of the Campbells' thirteen children, only three survived to adulthood, and the reported footsteps and moved objects get attributed to a family that endured extraordinary loss."
  },
  {
    "id": "H-013",
    "title": "Fabulous Fox Theatre",
    "city": "St. Louis",
    "state": "MO",
    "lat": 38.63911,
    "lon": -90.23135,
    "cluster": "St. Louis and Alton",
    "siteType": "Historic operating theatre",
    "phenomenon": "Theatre lore includes unexplained footsteps, voices, seat movement, and figures seen in backstage or balcony areas.",
    "evidence": "B - Established theatre folklore",
    "detourMiles": "4",
    "priority": "Strong",
    "visit": "Public theatre tour or performance",
    "access": "Backstage access is limited to tours and events. Check the current tour calendar.",
    "official": "https://www.fabulousfox.com/",
    "folklore": "https://www.stlouisghosts.com/haunted-places/fabulous-fox-theatre/",
    "history": "The 'Fabulous Fox' opened in 1929 as one of the most opulent movie palaces ever built — a Siamese-Byzantine fantasy with a 2,000-pound glass chandelier. Restored in 1982 after near-demolition, it's a working Broadway house where crews tell stories of a phantom projectionist and seats that flip on their own."
  },
  {
    "id": "H-014",
    "title": "McPike Mansion",
    "city": "Alton",
    "state": "IL",
    "lat": 38.90237,
    "lon": -90.18469,
    "cluster": "St. Louis and Alton",
    "siteType": "Restoration-stage historic mansion",
    "phenomenon": "Investigators and tour guests report apparitions, voices, touches, and activity in the cellar and former living areas.",
    "evidence": "A - Paranormal tours and investigations",
    "detourMiles": "20",
    "priority": "Must",
    "visit": "Scheduled history or paranormal tour",
    "access": "Active restoration site. Entry is by scheduled event or permission only.",
    "official": "https://www.mcpikemansion.com/",
    "folklore": "https://www.mcpikemansion.com/",
    "history": "Henry Guest McPike, an Alton mayor and horticulturist, built this Italianate mansion in 1869 on a hill above town. It's been slowly rescued from ruin by private owners for decades, and its vaulted wine cellar is the centerpiece of the ghost tours. Alton as a whole — a river town of Civil War prisons and cholera epidemics — calls itself one of the most haunted small towns in America."
  },
  {
    "id": "H-015",
    "title": "Mineral Springs Hotel Building",
    "city": "Alton",
    "state": "IL",
    "lat": 38.89108,
    "lon": -90.18109,
    "cluster": "St. Louis and Alton",
    "siteType": "Historic commercial building and former hotel",
    "phenomenon": "The building is associated with reports of voices, figures, splashing sounds, and activity around its former pool and hotel spaces.",
    "evidence": "B - Major Alton ghost-tour site",
    "detourMiles": "1",
    "priority": "Strong",
    "visit": "Booked Alton history or ghost tour",
    "access": "Tenants and access arrangements change. Do not assume unrestricted entry; book through a current operator.",
    "official": "https://www.altonhauntings.com/",
    "folklore": "https://www.altonhauntings.com/mineral-springs-hotel/",
    "history": "Built by the Luer meatpacking brothers in 1914 after workers struck a mineral spring digging an ice house, this hotel promised healing waters. Its swimming pool — once the largest in Illinois — is where the building's saddest legends live. It's now shops and event space, with the old pool a stop on every Alton ghost tour."
  },
  {
    "id": "H-016",
    "title": "Inn at 835",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.79315,
    "lon": -89.65076,
    "cluster": "Springfield",
    "siteType": "Historic operating inn",
    "phenomenon": "Guests have described perfume-like scents, footsteps, doors behaving oddly, and a woman's presence linked by folklore to the original owner.",
    "evidence": "B - Established inn folklore",
    "detourMiles": "2",
    "priority": "Strong",
    "visit": "Overnight stay",
    "access": "Operating lodging. Public and guest spaces only.",
    "official": "https://www.innat835.com/",
    "folklore": "https://www.hauntedrooms.com/illinois/haunted-places/haunted-hotels/inn-at-835-springfield",
    "history": "Bell Miller, a self-made businesswoman who built Springfield's biggest floral company, commissioned this Classical Revival building in 1909 with apartments above her flower business. It's now a bed-and-breakfast whose staff report gentle, housekeeping-style phenomena — doors, lights, the smell of flowers — attributed affectionately to Bell herself."
  },
  {
    "id": "H-017",
    "title": "Dana-Thomas House",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.79461,
    "lon": -89.6502,
    "cluster": "Springfield",
    "siteType": "Frank Lloyd Wright historic house",
    "phenomenon": "Guides and visitors have circulated stories of unexplained footsteps, sounds, and a presence in the richly detailed house.",
    "evidence": "C - Local legend",
    "detourMiles": "0.4",
    "priority": "Strong",
    "visit": "Daytime architectural tour",
    "access": "Guided entry only. Historic stairs and narrow areas may affect accessibility.",
    "official": "https://dnrhistoric.illinois.gov/experience/sites/site.dana-thomas-house.html",
    "folklore": "https://www.hauntedplaces.org/item/dana-thomas-house/",
    "history": "Frank Lloyd Wright designed this house in 1902 for Susan Lawrence Dana, a wealthy widow and one of his most daring clients — it's one of the best-preserved early Wright interiors anywhere, with over 100 pieces of original furniture. Dana lost her fortune, turned to spiritualism, and held séances in the house; she died in poverty while the house survived intact."
  },
  {
    "id": "H-018",
    "title": "Lincoln Tomb and Oak Ridge Cemetery",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.82028,
    "lon": -89.67566,
    "cluster": "Springfield",
    "siteType": "Historic tomb and cemetery",
    "phenomenon": "Springfield ghost lore includes unexplained sounds and sensed presences near historic graves, while the tomb itself provides a solemn, atmospheric stop.",
    "evidence": "C - Local folklore and atmosphere",
    "detourMiles": "3",
    "priority": "Strong",
    "visit": "Respectful daylight visit",
    "access": "Follow cemetery and historic-site hours. No nighttime wandering or intrusive investigation.",
    "official": "https://dnrhistoric.illinois.gov/experience/sites/site.lincoln-tomb.html",
    "folklore": "https://springfieldwalks.com/",
    "history": "Lincoln's tomb holds a genuinely wild true story: in 1876 a Chicago counterfeiting gang tried to steal his body and ransom it. They were caught mid-heist, and Lincoln's coffin was later encased in concrete to end the threat. Visitors rub the nose of the bronze bust for luck, and Oak Ridge is the second-most-visited cemetery in America after Arlington."
  },
  {
    "id": "H-019",
    "title": "Old Joliet Prison",
    "city": "Joliet",
    "state": "IL",
    "lat": 41.54856,
    "lon": -88.07396,
    "cluster": "Joliet and Chicago outskirts",
    "siteType": "Historic decommissioned prison",
    "phenomenon": "Visitors report footsteps, voices, shadows, and a heavy atmosphere in the cell houses and administrative buildings.",
    "evidence": "A - Historic tours plus paranormal reputation",
    "detourMiles": "2",
    "priority": "Must",
    "visit": "Historic guided or self-guided tour",
    "access": "Seasonal ticketed site, generally spring through fall. This recommendation is the historic prison, not a staged Halloween attraction.",
    "official": "https://www.jolietprison.org/tours.html",
    "folklore": "https://www.wbez.org/culture-the-arts/2018/10/26/is-the-old-joliet-prison-haunted",
    "history": "Old Joliet Prison opened in 1858, its limestone walls quarried by the convicts themselves. It ran until 2002, held everyone from Leopold and Loeb to Richard Speck, and its castle-like front gate is famous worldwide from The Blues Brothers. Tours today walk the cellblocks that stood through 144 years of hard history."
  },
  {
    "id": "H-020",
    "title": "Rialto Square Theatre",
    "city": "Joliet",
    "state": "IL",
    "lat": 41.52694,
    "lon": -88.08166,
    "cluster": "Joliet and Chicago outskirts",
    "siteType": "Historic operating theatre",
    "phenomenon": "Theatre stories include a young figure, phantom movement, and unexplained sounds in backstage and balcony areas.",
    "evidence": "B - Long-running theatre folklore",
    "detourMiles": "2",
    "priority": "Strong",
    "visit": "Performance, architecture tour, or special event",
    "access": "Public access depends on shows and scheduled tours. Backstage areas are restricted.",
    "official": "https://rialtosquare.com/",
    "folklore": "https://www.hauntedplaces.org/item/rialto-square-theatre/",
    "history": "The Rialto opened in 1926 as a 'palace for the people' — an over-the-top Vaudeville house modeled on Versailles, with one of the largest hand-cut crystal chandeliers in the country. Its resident ghost story is a woman in white the staff call Rachel, said to drift the balcony during quiet hours."
  },
  {
    "id": "H-021",
    "title": "Bachelor's Grove Cemetery",
    "city": "Midlothian",
    "state": "IL",
    "lat": 41.6309,
    "lon": -87.7709,
    "cluster": "Joliet and Chicago outskirts",
    "siteType": "Small historic cemetery in forest preserve",
    "phenomenon": "A famous Chicago-area legend involving phantom vehicles, lights, figures, and a woman sometimes reported near the graves.",
    "evidence": "B - Famous regional folklore",
    "detourMiles": "14",
    "priority": "Optional",
    "visit": "Quiet daylight walk only",
    "access": "Use legal forest-preserve parking and trails. Respect graves, posted hours, and all closure signs. Do not visit after dark.",
    "official": "https://fpdcc.com/places/locations/rubio-woods/",
    "folklore": "https://www.bachelorsgrove.com/",
    "history": "A small settlers' burial ground from the 1840s, abandoned as its community faded, vandalized for decades, and now surrounded by forest preserve. Bachelor's Grove is arguably the most famous haunted cemetery in America — the 'white lady' photograph taken here in 1991 is one of the most reproduced ghost photos ever. The lagoon next to it was reputedly a mob dumping ground in the 1920s."
  },
  {
    "id": "H-022",
    "title": "Resurrection Cemetery, Resurrection Mary legend",
    "city": "Justice",
    "state": "IL",
    "lat": 41.75552,
    "lon": -87.83877,
    "cluster": "Joliet and Chicago outskirts",
    "siteType": "Operating cemetery and roadside legend",
    "phenomenon": "For decades, drivers have reported a young woman in pale clothing along Archer Avenue who vanishes near the cemetery gates.",
    "evidence": "B - Classic Chicago-area legend",
    "detourMiles": "12",
    "priority": "Optional",
    "visit": "Daylight cemetery visit or legal drive-by",
    "access": "Active sacred cemetery. Visit only during posted hours, do not block roads, and do not approach strangers or stage roadside encounters.",
    "official": "https://www.catholiccemeterieschicago.org/Locations/Details/Resurrection",
    "folklore": "https://www.chicagohistory.org/resurrection-mary/",
    "history": "Resurrection Mary is Chicago's signature ghost story: since the 1930s, drivers on Archer Avenue have told of picking up a young blonde woman in a white party dress who asks to be let out at Resurrection Cemetery's gates — and vanishes. She's usually linked to a young woman killed walking home from the Oh Henry Ballroom. The bent bars on the cemetery gate became part of the legend."
  },
  {
    "id": "H-023",
    "title": "Old Lake County Jail",
    "city": "Crown Point",
    "state": "IN",
    "lat": 41.41657,
    "lon": -87.36556,
    "cluster": "Northwest Indiana",
    "siteType": "Historic jail museum",
    "phenomenon": "The jail's tours describe footsteps, voices, cold areas, and unexplained motion inside the cellblocks and former living quarters.",
    "evidence": "A - Current ghost tours",
    "detourMiles": "7",
    "priority": "Must",
    "visit": "Scheduled ghost or history tour",
    "access": "Entry is by tour or event. Check age guidance and current dates.",
    "official": "https://www.southshorecva.com/listing/old-lake-county-jail/247/",
    "folklore": "https://www.southshorecva.com/blog/post/haunted-old-lake-county-jail/",
    "history": "This 1882 jail earned its place in history on March 3, 1934, when John Dillinger — America's most famous bank robber — broke out using a fake gun reportedly carved from wood and blackened with shoe polish, then drove off in the sheriff's own car. The museum tours cover the escape cell and the crime-wave era it belongs to."
  },
  {
    "id": "H-024",
    "title": "Diana of the Dunes Dare, West Beach",
    "city": "Gary",
    "state": "IN",
    "lat": 41.62235,
    "lon": -87.2073,
    "cluster": "Indiana Dunes",
    "siteType": "National park dune trail and ghost legend",
    "phenomenon": "The National Park Service retells the legend of Alice Mabel Gray, Diana of the Dunes, whose solitary life inspired later ghost stories in the dunes.",
    "evidence": "A - NPS acknowledges the ghost story",
    "detourMiles": "3",
    "priority": "Must",
    "visit": "Sunset hike while the park is open",
    "access": "Park fees and seasonal parking controls may apply. Stay on marked trails and confirm closing time before a sunset visit.",
    "official": "https://www.nps.gov/thingstodo/dianadunesdare.htm",
    "folklore": "https://www.nps.gov/thingstodo/dianadunesdare.htm",
    "history": "Diana of the Dunes was a real person: Alice Mabel Gray, a University of Chicago-educated woman who in 1915 walked away from city life to live alone in a driftwood shack among the dunes. Newspapers turned her into a legend while she lived; after her death in 1925 the legend turned ghostly — swimmers say she still walks the West Beach shoreline at dusk."
  },
  {
    "id": "H-025",
    "title": "Barker Mansion",
    "city": "Michigan City",
    "state": "IN",
    "lat": 41.71466,
    "lon": -86.90008,
    "cluster": "Michigan City",
    "siteType": "Historic mansion museum",
    "phenomenon": "Local reports describe footsteps, voices, and movement in rooms associated with the Barker family and household staff.",
    "evidence": "B - Established local folklore",
    "detourMiles": "3",
    "priority": "Strong",
    "visit": "Guided mansion tour",
    "access": "Tour availability varies by season and restoration work.",
    "official": "https://www.barkermansion.com/",
    "folklore": "https://www.hauntedplaces.org/item/barker-mansion/",
    "history": "John H. Barker made his fortune building railroad freight cars — at peak his Michigan City works turned out thousands a year. His 38-room mansion, finished in 1905, went to his daughter Catherine, orphaned at 14. Staff and visitors report a woman in period dress and a girl on the stairs; the mansion runs its own after-dark history tours."
  },
  {
    "id": "H-026",
    "title": "Old Lighthouse Museum",
    "city": "Michigan City",
    "state": "IN",
    "lat": 41.72184,
    "lon": -86.90548,
    "cluster": "Michigan City",
    "siteType": "Historic lighthouse museum",
    "phenomenon": "Paranormal programs and local accounts cite footsteps, voices, and a keeper-like presence in the lighthouse residence.",
    "evidence": "A - Hosted paranormal investigations",
    "detourMiles": "2",
    "priority": "Must",
    "visit": "Museum tour or scheduled investigation",
    "access": "Seasonal museum. Check stairs, tour hours, and special-event rules.",
    "official": "https://michigancitylighthousemuseum.com/",
    "folklore": "https://michigancitylighthousemuseum.com/events/",
    "history": "Michigan City's 1858 lighthouse was kept for 43 years by Harriet Colfax, one of the most celebrated female lighthouse keepers in American history — she hauled oil up the tower into her 80s. The museum's ghost stories usually feature Harriet still tending her light, along with echoes of the 1886 wreck of the J.D. Marshall offshore."
  },
  {
    "id": "H-027",
    "title": "Washington Hall, University of Notre Dame",
    "city": "Notre Dame",
    "state": "IN",
    "lat": 41.70331,
    "lon": -86.23952,
    "cluster": "South Bend",
    "siteType": "Historic campus theatre",
    "phenomenon": "Notre Dame sources preserve a century-old campus legend involving footsteps, sounds, and a figure associated by tradition with George Gipp.",
    "evidence": "A - University preserves the folklore",
    "detourMiles": "3",
    "priority": "Must",
    "visit": "Exterior campus stop or public event",
    "access": "Campus access is generally possible, but interior access depends on events and university rules.",
    "official": "https://washingtonhall.nd.edu/about-washington-hall/",
    "folklore": "https://al.nd.edu/news/latest-news/a-history-of-washington-halland-of-notre-dame/",
    "history": "Washington Hall is Notre Dame's Victorian-era theater, and its ghost is campus legend: George Gipp — 'the Gipper' himself, Knute Rockne's star player — reputedly slept on the hall's steps one cold night in 1920, caught the illness that killed him weeks later, and has been blamed for footsteps and slamming doors in the building ever since."
  },
  {
    "id": "H-028",
    "title": "Tippecanoe Place",
    "city": "South Bend",
    "state": "IN",
    "lat": 41.6758,
    "lon": -86.25787,
    "cluster": "South Bend",
    "siteType": "Historic mansion restaurant",
    "phenomenon": "Staff and guest stories include footsteps, voices, a woman's figure, and movement in less-used parts of the former Studebaker mansion.",
    "evidence": "B - Established local folklore",
    "detourMiles": "1",
    "priority": "Strong",
    "visit": "Meal or public historic space",
    "access": "Operating restaurant and event venue. Private rooms and upper areas may be restricted.",
    "official": "https://www.tippe.com/",
    "folklore": "https://www.visitsouthbend.com/blog/strange-things-in-south-bend-mishawaka/",
    "history": "Tippecanoe Place is the 40-room granite mansion Clement Studebaker — of the wagon-and-automobile dynasty — completed in 1889. It survived fire and decades of institutional use before becoming a restaurant, where servers trade stories of Victorian figures on the grand staircase after closing."
  },
  {
    "id": "H-029",
    "title": "Morris Performing Arts Center",
    "city": "South Bend",
    "state": "IN",
    "lat": 41.67794,
    "lon": -86.25064,
    "cluster": "South Bend",
    "siteType": "Historic operating theatre",
    "phenomenon": "The venue's own ghost tours describe mysterious footsteps, lights, taps, and activity in the basement, stage wings, and former tunnel areas.",
    "evidence": "A - Official ghost tours",
    "detourMiles": "1",
    "priority": "Must",
    "visit": "Ghost tour when scheduled, otherwise theatre tour",
    "access": "Regular tours are available by arrangement. Ghost tours are typically seasonal, so verify the 2026 calendar.",
    "official": "https://morriscenter.org/plan-your-visit/tours/",
    "folklore": "https://morriscenter.org/event/ghost-tours/2025-09-19/1/",
    "history": "Opened in 1922 as the Palace Theatre, this ornate house survived a near-demolition and reopened as the Morris. Its longtime backstage legend is a spectral usher and an organist heard when the house is empty — the kind of story every century-old theater accumulates, told here with unusual consistency."
  },
  {
    "id": "H-030",
    "title": "Henderson Castle",
    "city": "Kalamazoo",
    "state": "MI",
    "lat": 42.29251,
    "lon": -85.59446,
    "cluster": "Kalamazoo",
    "siteType": "Historic operating inn and event venue",
    "phenomenon": "Guests and investigators report apparitions, voices, footsteps, and activity in guest rooms and former family areas.",
    "evidence": "B - Widely reported hotel folklore",
    "detourMiles": "3",
    "priority": "Must",
    "visit": "Tour, meal, or overnight",
    "access": "Operating inn and event venue. Reserve ahead and respect guest privacy.",
    "official": "https://www.hendersoncastle.com/",
    "folklore": "https://www.mlive.com/news/kalamazoo/2019/10/is-henderson-castle-haunted.html",
    "history": "Frank Henderson made his money selling uniforms and regalia to fraternal lodges, and in 1895 crowned Kalamazoo's West Main Hill with this Queen Anne castle — Tiffany windows, a ballroom, and a third-floor tower. He died just four years after moving in. Now an inn, it embraces its reputation openly with resident-ghost lore about Frank and a former caretaker."
  },
  {
    "id": "H-031",
    "title": "Kalamazoo State Theatre",
    "city": "Kalamazoo",
    "state": "MI",
    "lat": 42.28798,
    "lon": -85.58286,
    "cluster": "Kalamazoo",
    "siteType": "Historic operating theatre",
    "phenomenon": "Local accounts describe a stage statue that appears to shift, voices, music, and other sounds heard when the building is quiet.",
    "evidence": "C - Local legend",
    "detourMiles": "1",
    "priority": "Strong",
    "visit": "Performance or authorized tour",
    "access": "Interior access is event-dependent. Do not attempt backstage access without permission.",
    "official": "https://kalamazoostate.com/",
    "folklore": "https://www.michiganhauntedhouses.com/real-haunt/kalamazoo-state-theatre.html",
    "history": "The State opened in 1927, a John Eberson 'atmospheric' theater built to feel like sitting in a Mediterranean courtyard under a night sky of twinkling lights. Its staff ghost is 'Thelma,' a former employee said to watch shows from the balcony — crews leave a seat for her."
  },
  {
    "id": "H-032",
    "title": "The English Inn",
    "city": "Eaton Rapids",
    "state": "MI",
    "lat": 42.55602,
    "lon": -84.65755,
    "cluster": "Lansing approach",
    "siteType": "Historic operating inn and restaurant",
    "phenomenon": "Regional stories describe footsteps, objects moving, and a woman-like presence in the manor and guest areas.",
    "evidence": "C - Local inn folklore",
    "detourMiles": "8",
    "priority": "Optional",
    "visit": "Meal or overnight",
    "access": "Operating hospitality property. Public and booked guest areas only.",
    "official": "https://www.englishinn.com/directions",
    "folklore": "https://www.hauntedplaces.org/item/the-english-inn/",
    "history": "This riverside Tudor mansion was built in 1927 as 'Medovue,' the home of Irving Reuter, general manager of Oldsmobile, and his wife Janet. The Reuters' fortunes fell with the Depression; the house passed through many hands before becoming an inn and restaurant, where Janet is the name attached to most of the gentle goings-on."
  },
  {
    "id": "H-033",
    "title": "Turner-Dodge House",
    "city": "Lansing",
    "state": "MI",
    "lat": 42.75087,
    "lon": -84.54827,
    "cluster": "Lansing",
    "siteType": "City-owned historic house",
    "phenomenon": "The mansion is a recurring Lansing ghost-tour stop, with stories of footsteps, sounds, and sensed presences in upper rooms.",
    "evidence": "B - Included in local ghost programming",
    "detourMiles": "2",
    "priority": "Strong",
    "visit": "Historic tour or scheduled event",
    "access": "City facility. Interior access is limited to tours, rentals, and public events.",
    "official": "https://www.lansingmi.gov/461/Turner-Dodge-House",
    "folklore": "https://www.michigan.org/property/lansing-ghost-tour-lawless-legends-and-laments-lanternlight",
    "history": "James Turner was one of Lansing's founding businessmen, and his daughter's family, the Dodges, expanded this Grand River mansion around 1900 with architect Darius Moon. It later spent years as a school and community building — the layered institutional history is where its footsteps-and-voices stories come from. The city now runs it and hosts history and paranormal programs."
  },
  {
    "id": "H-034",
    "title": "Michigan State Capitol",
    "city": "Lansing",
    "state": "MI",
    "lat": 42.73364,
    "lon": -84.55533,
    "cluster": "Lansing",
    "siteType": "Historic government building",
    "phenomenon": "Lansing ghost tours repeat reports of strange sounds and lingering presences after hours in the Victorian-era Capitol.",
    "evidence": "B - Recognized local ghost-tour stop",
    "detourMiles": "1",
    "priority": "Strong",
    "visit": "Free daytime tour",
    "access": "Security screening applies. Public hours are generally weekdays and the first Saturday of each month; verify current schedule.",
    "official": "https://capitol.michigan.gov/tours",
    "folklore": "https://www.michigan.org/property/lansing-ghost-tour-lawless-legends-and-laments-lanternlight",
    "history": "Michigan's 1879 Capitol was one of the first state capitols built after the Civil War to be deliberately fireproof — which is ironic given its ghost stories center on a night watchman devoted to the building. Its restored Victorian interior, all hand-painted illusion work, is genuinely one of the finest in the country."
  },
  {
    "id": "H-035",
    "title": "Pere Cheney Ghost Town and Cemetery",
    "city": "Grayling area",
    "state": "MI",
    "lat": 44.5731,
    "lon": -84.6364,
    "cluster": "Grayling",
    "siteType": "Abandoned settlement site and cemetery",
    "phenomenon": "The vanished logging settlement has accumulated stories of phantom voices, lights, and a mysterious woman, layered over the real history of a town lost to disease and economic decline.",
    "evidence": "B - Famous northern Michigan legend",
    "detourMiles": "8",
    "priority": "Must",
    "visit": "Daylight historical stop",
    "access": "Use public roads and marked access only. Roads can be sandy or muddy. Do not enter private parcels, disturb graves, or remain after dark.",
    "official": "https://www.michigan.gov/libraryofmichigan/public/michigan/county-guides/guides/crawford",
    "folklore": "https://www.michiganpublic.org/offbeat/2017-07-12/how-did-pere-cheney-become-a-ghost-town",
    "history": "Pere Cheney was a real lumber town of several hundred people founded in the 1870s — and diphtheria epidemics in the 1890s emptied it. By the 1910s it was gone; today only the cemetery remains in the pines, with broken headstones and a century of witch-and-curse legends layered over a very real story of a town that sickness erased."
  },
  {
    "id": "H-036",
    "title": "Colonial Michilimackinac",
    "city": "Mackinaw City",
    "state": "MI",
    "lat": 45.78657,
    "lon": -84.72717,
    "cluster": "Straits of Mackinac",
    "siteType": "Reconstructed eighteenth-century fort",
    "phenomenon": "The fort's long military and trading history has produced stories of footsteps, voices, and figures in reconstructed buildings, especially during quiet hours.",
    "evidence": "B - Historic-site folklore",
    "detourMiles": "0",
    "priority": "Must",
    "visit": "Daytime fort tour",
    "access": "Seasonal ticketed attraction. Special spooky programs can be more theatrical than the rest of this list, so choose the regular history visit.",
    "official": "https://www.mackinacparks.com/attraction/colonial-michilimackinac/",
    "folklore": "https://www.mackinacparks.com/event/fort-fright/",
    "history": "The fort at the Straits dates to 1715, and its darkest true chapter is the 1763 attack during Pontiac's War, when Ojibwe warriors used a game of baggatiway (lacrosse) to get inside the palisade and overwhelm the British garrison. Archaeologists have dug here every summer since 1959; the reconstructed fort's ghost stories borrow from a genuinely violent history."
  },
  {
    "id": "H-037",
    "title": "Old Mackinac Point Lighthouse",
    "city": "Mackinaw City",
    "state": "MI",
    "lat": 45.78864,
    "lon": -84.73255,
    "cluster": "Straits of Mackinac",
    "siteType": "Historic lighthouse museum",
    "phenomenon": "Keeper-era stories, shipwreck history, wind, fog signals, and isolated rooms make this a strong atmospheric lighthouse stop, with occasional local ghost reports.",
    "evidence": "C - Lighthouse folklore and atmosphere",
    "detourMiles": "0.5",
    "priority": "Must",
    "visit": "Lighthouse and tower tour",
    "access": "Seasonal hours. Tower access involves stairs and may be weather-dependent.",
    "official": "https://www.mackinacparks.com/attraction/old-mackinac-point-lighthouse/",
    "folklore": "https://www.mackinacparks.com/attraction/old-mackinac-point-lighthouse/",
    "history": "The 1892 'Castle of the Straits' guided ships through some of the deadliest water on the Great Lakes until 1957, when the new Mackinac Bridge's lights made it obsolete. Keeper George Marshall and his family tended the light for decades — museum staff attribute the footsteps on the tower stairs to a keeper who never stopped his rounds."
  },
  {
    "id": "H-038",
    "title": "Cheboygan Opera House",
    "city": "Cheboygan",
    "state": "MI",
    "lat": 45.64619,
    "lon": -84.47457,
    "cluster": "Cheboygan ferry staging",
    "siteType": "Historic operating theatre",
    "phenomenon": "The venue's own history materials reference ghosts and unexplained stories alongside its long vaudeville and civic history.",
    "evidence": "A - Venue acknowledges ghost lore",
    "detourMiles": "1",
    "priority": "Strong",
    "visit": "Performance or authorized tour",
    "access": "Interior access depends on performances and events. This is close to the Bois Blanc ferry staging area.",
    "official": "https://theoperahouse.org/",
    "folklore": "https://theoperahouse.org/book/",
    "history": "Cheboygan's opera house first rose in 1877, burned, and was rebuilt in 1888 — a frontier lumber town's bid for culture, hosting everyone from Annie Oakley (by local tradition) to touring Victorian troupes. Restored by the community, it keeps a classic theater-ghost tradition of a performer who never left the stage."
  },
  {
    "id": "H-039",
    "title": "Mission Point Resort",
    "city": "Mackinac Island",
    "state": "MI",
    "lat": 45.84921,
    "lon": -84.60356,
    "cluster": "Optional Mackinac Island branch",
    "siteType": "Operating island resort",
    "phenomenon": "The resort has a long reputation for a young man's apparition and unexplained activity around its theatre and older college-era spaces.",
    "evidence": "B - Widely reported resort folklore",
    "detourMiles": "0",
    "priority": "Optional",
    "visit": "Separate Mackinac Island overnight or day trip",
    "access": "Not on the Bois Blanc ferry route. This requires a separate passenger ferry from Mackinaw City or St. Ignace and several hours of added logistics.",
    "official": "https://www.missionpoint.com/our-resort",
    "folklore": "https://www.audacy.com/wwjnewsradio/news/local/mission-point-resort-on-mackinac-island-has-a-famous-ghost",
    "history": "Mission Point's sprawling grounds began as the world headquarters of Moral Re-Armament, a postwar spiritual movement that built the soaring timber-lodge theater in the 1950s, and later briefly housed a college. The resort's famous ghost is 'Harvey,' a heartbroken student of that era whose story staff share freely — guests report him mostly in the theater wing."
  },
  {
    "id": "H-040",
    "title": "Bois Blanc Island Lighthouse",
    "city": "Bois Blanc Island",
    "state": "MI",
    "lat": 45.81,
    "lon": -84.42,
    "cluster": "Bois Blanc Island destination",
    "siteType": "Deactivated historic lighthouse, private residence",
    "phenomenon": "This is primarily an isolated and atmospheric maritime site rather than a strongly documented haunting. Its history includes storms, lost earlier towers, keeper life, and long periods of remoteness.",
    "evidence": "D - Atmospheric, limited haunting claims",
    "detourMiles": "17",
    "priority": "Destination",
    "visit": "View from public water or legal public vantage",
    "access": "The historic lighthouse is privately owned. Do not enter or approach private property. Island roads are mostly unpaved and conditions vary.",
    "official": "https://www.history.uscg.mil/Browse-by-Topic/Assets/Land/Lighthouses-Light-Stations/Article/1900384/bois-blanc-island-light/",
    "folklore": "https://www.us-lighthouses.com/bois-blanc-island-lighthouse",
    "history": "A light was first established on Bois Blanc in 1829 — one of the earliest on the Great Lakes — and the surviving 1867 tower replaced earlier ones claimed by storm and erosion. Its most dramatic true story belongs to an early keeper's daughter who reputedly kept the light burning alone through a storm after her father was lost crossing the ice. Deactivated in the 1920s, it's now a private residence: view respectfully from the road or shore."
  },
  {
    "id": "H-041",
    "title": "Union Miners Cemetery",
    "city": "Mount Olive",
    "state": "IL",
    "lat": 39.0674,
    "lon": -89.7361,
    "cluster": "Illinois corridor",
    "siteType": "Historic labor cemetery",
    "phenomenon": "Visitors and caretakers describe a heavy, watched feeling near the Mother Jones monument, especially at dusk.",
    "evidence": "C - Local atmosphere and lore",
    "detourMiles": "3",
    "priority": "Moderate",
    "visit": "Daylight, respectful walk-through",
    "access": "Public cemetery, open during daylight hours. No fee.",
    "official": "https://www.nps.gov/places/union-miners-cemetery.htm",
    "folklore": "https://www.nps.gov/places/union-miners-cemetery.htm",
    "history": "Founded in 1899 for coal miners killed in a labor uprising, this is the only cemetery in the country owned and run by a labor union rather than a church or city. Labor organizer Mother Jones asked to be buried here among 'her boys' and is — her grave is the tallest monument in the yard, guarded by two bronze miners."
  },
  {
    "id": "H-042",
    "title": "Funks Grove",
    "city": "Shirley",
    "state": "IL",
    "lat": 40.4989,
    "lon": -89.0068,
    "cluster": "Illinois corridor",
    "siteType": "Ghost town",
    "phenomenon": "Travelers describe an eerie stillness at the abandoned depot and general store, swallowed by trees where a real town used to be.",
    "evidence": "C - Atmosphere of an abandoned settlement",
    "detourMiles": "2",
    "priority": "Moderate",
    "visit": "Daylight walk past the old depot and store",
    "access": "Public road frontage; respect any posted private property.",
    "official": "https://funksmaplesirup.com/",
    "folklore": "https://savingplaces.org/guides/ghost-towns-on-route-66",
    "history": "Founded in 1824 by the Funk family, this was once a busy railroad stopover famous for its maple syrup. The town emptied out over the decades — today the old general store and train depot sit abandoned among the trees, while the Funk family, seven generations later, still boils syrup a quarter mile away."
  },
  {
    "id": "H-043",
    "title": "Elkhart Cemetery",
    "city": "Elkhart",
    "state": "IL",
    "lat": 40.1469,
    "lon": -89.4739,
    "cluster": "Illinois corridor",
    "siteType": "Historic hilltop cemetery",
    "phenomenon": "Visitors report cold spots and a sense of being watched among the older 1800s headstones on the hill.",
    "evidence": "C - Local folklore",
    "detourMiles": "4",
    "priority": "Moderate",
    "visit": "Daylight visit only",
    "access": "Public cemetery on Elkhart Hill. No fee.",
    "official": "https://www.hallwalkabout.com/il/elkhart/",
    "folklore": "https://www.hallwalkabout.com/il/elkhart/",
    "history": "This hilltop cemetery holds generations of one of central Illinois's oldest settler families, including relatives of Mary Todd Lincoln. The hill itself is a rare glacial landform rising sharply out of flat farmland, which locals have always found a little unsettling after dark."
  },
  {
    "id": "H-044",
    "title": "Old State Capitol",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.7995,
    "lon": -89.644,
    "cluster": "Illinois corridor",
    "siteType": "Historic government building",
    "phenomenon": "Staff and visitors describe footsteps in empty upper chambers, tied to the building's role in Lincoln's story.",
    "evidence": "C - Local folklore",
    "detourMiles": "2",
    "priority": "Moderate",
    "visit": "Daytime guided tour",
    "access": "State historic site, open for tours; check seasonal hours.",
    "official": "https://www.illinois.gov/dnr/experience/parks/pages/oldstatecapitol.aspx",
    "folklore": "https://www.illinois.gov/dnr/experience/parks/pages/oldstatecapitol.aspx",
    "history": "Lincoln delivered his famous 'House Divided' speech here in 1858, and in 1865 his body lay in state in this very building as tens of thousands filed past to say goodbye. Few buildings in America carry that much grief under one roof."
  },
  {
    "id": "H-045",
    "title": "Camp Butler National Cemetery",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.7756,
    "lon": -89.5322,
    "cluster": "Illinois corridor",
    "siteType": "Civil War national cemetery",
    "phenomenon": "Visitors describe an unusually heavy stillness among the Civil War-era sections, where thousands of soldiers and prisoners are buried.",
    "evidence": "C - Atmosphere of a wartime burial ground",
    "detourMiles": "5",
    "priority": "Moderate",
    "visit": "Daylight, respectful walk",
    "access": "Public national cemetery, open daily during daylight hours.",
    "official": "https://www.cem.va.gov/cems/nchp/campbutler.asp",
    "folklore": "https://www.cem.va.gov/cems/nchp/campbutler.asp",
    "history": "Camp Butler was a Union training camp and, later, a prisoner-of-war camp during the Civil War. Roughly 1,000 Confederate prisoners who died here of disease are buried in a mass section alongside thousands of Union soldiers — a wartime tragedy on both sides of the same fence line."
  },
  {
    "id": "H-046",
    "title": "Macoupin County Courthouse",
    "city": "Carlinville",
    "state": "IL",
    "lat": 39.2814,
    "lon": -89.8843,
    "cluster": "Illinois corridor",
    "siteType": "Historic courthouse",
    "phenomenon": "Local lore ties restless energy in the building to the corruption scandal that bankrupted the county to build it.",
    "evidence": "C - Local legend tied to a real scandal",
    "detourMiles": "6",
    "priority": "Moderate",
    "visit": "Daylight exterior and grounds visit",
    "access": "Public building grounds; check hours for interior access.",
    "official": "https://www.macoupincountyil.gov/",
    "folklore": "https://www.macoupincountyil.gov/",
    "history": "Nicknamed the 'Million Dollar Courthouse,' this 1870 building bankrupted Macoupin County for nearly 40 years after costs spiraled wildly over budget amid corruption allegations. It's one of the most infamous cautionary tales in Illinois local government history — a courthouse the county could barely afford to keep."
  },
  {
    "id": "H-047",
    "title": "Old Chain of Rocks Bridge",
    "city": "Madison",
    "state": "IL",
    "lat": 38.7739,
    "lon": -90.1734,
    "cluster": "Illinois corridor",
    "siteType": "Abandoned bridge",
    "phenomenon": "The bridge's decades of abandonment and a well-known real crime from the 1950s give it a lasting eerie reputation among Route 66 travelers.",
    "evidence": "B - Documented history plus established Route 66 lore",
    "detourMiles": "4",
    "priority": "Strong",
    "visit": "Daylight walk across the pedestrian bridge",
    "access": "Public pedestrian/bike bridge, open daily, no fee.",
    "official": "https://www.nps.gov/places/chain-of-rocks-bridge.htm",
    "folklore": "https://en.wikipedia.org/wiki/Chain_of_Rocks_Bridge",
    "history": "Built in 1929 with an unusual 22-degree bend in the middle, this mile-long bridge carried Route 66 traffic until 1968, then sat abandoned and slated for demolition for over 20 years before reopening as a pedestrian path in 1999. Its long empty decades and dramatic mid-river turn have made it one of the most photographed — and most talked-about — spots on the entire Mother Road."
  },
  {
    "id": "H-048",
    "title": "Cahokia Courthouse",
    "city": "Cahokia",
    "state": "IL",
    "lat": 38.5661,
    "lon": -90.1912,
    "cluster": "Illinois corridor",
    "siteType": "Historic courthouse",
    "phenomenon": "As one of the oldest buildings in the Midwest, it carries centuries of local ghost-story tradition tied to its long use as a courthouse and jail.",
    "evidence": "C - Local folklore layered on a genuinely old building",
    "detourMiles": "5",
    "priority": "Moderate",
    "visit": "Daytime tour",
    "access": "State historic site; check seasonal hours.",
    "official": "https://cahokiacourthouse.org/",
    "folklore": "https://cahokiacourthouse.org/",
    "history": "Built around 1740 as a French colonial home, this building later served as a courthouse for the Northwest Territory — making it one of the oldest surviving buildings west of the Allegheny Mountains. Trials, sentencing, and courthouse business happened inside these walls for well over a century."
  },
  {
    "id": "H-049",
    "title": "Ariston Cafe",
    "city": "Litchfield",
    "state": "IL",
    "lat": 39.1751,
    "lon": -89.654,
    "cluster": "Illinois corridor",
    "siteType": "Historic Route 66 diner",
    "phenomenon": "Staff talk of an old-timer regular still lingering in the dining room decades after the cafe's earliest years.",
    "evidence": "C - Staff lore at a century-old business",
    "detourMiles": "3",
    "priority": "Moderate",
    "visit": "Have a meal, ask staff about the stories",
    "access": "Open restaurant, normal business hours.",
    "official": "https://www.ariston-cafe.com/",
    "folklore": "https://www.ariston-cafe.com/",
    "history": "Opened in 1924 and moved twice to keep up with Route 66's shifting path, the Ariston Cafe is the oldest continuously operating restaurant on the entire Mother Road. It survived the Depression, multiple highway realignments, and nearly a century of changing owners in the same family line."
  },
  {
    "id": "H-050",
    "title": "Pere Marquette State Park",
    "city": "Grafton",
    "state": "IL",
    "lat": 38.9758,
    "lon": -90.4315,
    "cluster": "Illinois corridor",
    "siteType": "State park with historic lodge",
    "phenomenon": "The historic lodge and surrounding bluffs carry local legends of a phantom hiker seen along the river trails at dusk.",
    "evidence": "C - Local folklore",
    "detourMiles": "8",
    "priority": "Moderate",
    "visit": "Daylight visit; lodge stays available",
    "access": "State park, open daily; lodge requires reservation.",
    "official": "https://www2.illinois.gov/dnr/parks/pages/peremarquette.aspx",
    "folklore": "https://www2.illinois.gov/dnr/parks/pages/peremarquette.aspx",
    "history": "Illinois's largest state park sits at the confluence of the Illinois and Mississippi Rivers, named for the French Jesuit explorer Father Jacques Marquette, who passed through the area in 1673. Its 1930s lodge was built by the Civilian Conservation Corps, and bald eagles now winter in the same bluffs Marquette once paddled beneath."
  },
  {
    "id": "H-051",
    "title": "Henry's Rabbit Ranch",
    "city": "Staunton",
    "state": "IL",
    "lat": 39.0136,
    "lon": -89.7898,
    "cluster": "Illinois corridor",
    "siteType": "Roadside oddity",
    "phenomenon": "Not a ghost story — a genuinely weird roadside stop with rusting VW Beetles staged as a 'rabbit family' along old Route 66.",
    "evidence": "A - Directly observable oddity",
    "detourMiles": "2",
    "priority": "Strong",
    "visit": "Quick photo stop",
    "access": "Free roadside attraction, viewable any time from the road.",
    "official": "https://route66insiders.com/henrys-rabbit-ranch/",
    "folklore": "https://route66insiders.com/henrys-rabbit-ranch/",
    "history": "A retired Route 66 enthusiast named Henry started keeping actual rabbits here and staged a family of vintage Volkswagen Beetles as 'rabbits' out front, complete with names and personalities. It's one of the most purely strange roadside stops left on the entire highway."
  },
  {
    "id": "H-052",
    "title": "Gemini Giant",
    "city": "Wilmington",
    "state": "IL",
    "lat": 41.3081,
    "lon": -88.1467,
    "cluster": "Illinois corridor",
    "siteType": "Roadside giant statue",
    "phenomenon": "A 28-foot spaceman statue has loomed over this stretch of Route 66 since the Space Race, unsettling in scale even by daylight.",
    "evidence": "A - Directly observable landmark",
    "detourMiles": "1",
    "priority": "Strong",
    "visit": "Quick photo stop",
    "access": "Free roadside stop; the statue is visible from the road.",
    "official": "https://www.illinoisroute66.org/gemini-giant",
    "folklore": "https://www.illinoisroute66.org/gemini-giant",
    "history": "This towering fiberglass 'muffler man' statue was custom-built in 1965 for the Launching Pad Drive-In, styled as a spaceman to celebrate NASA's Gemini program during the height of the Space Race. It has survived the restaurant's closure and reopening as one of the most recognized landmarks on the entire route."
  },
  {
    "id": "H-053",
    "title": "Ambler's Texaco Gas Station",
    "city": "Dwight",
    "state": "IL",
    "lat": 41.0947,
    "lon": -88.4292,
    "cluster": "Illinois corridor",
    "siteType": "Historic gas station",
    "phenomenon": "One of the most photographed and best-preserved 'ghost' stations left on the entire route — literally frozen in the 1930s-40s.",
    "evidence": "A - Preserved historic structure",
    "detourMiles": "1",
    "priority": "Strong",
    "visit": "Quick photo stop and walk-through",
    "access": "Free to view; restored and open seasonally.",
    "official": "https://www.illinoisroute66.org/amblers-texaco",
    "folklore": "https://www.illinoisroute66.org/amblers-texaco",
    "history": "Operating continuously from 1933 to 1999, this is one of the longest-running gas stations to have ever served Route 66 travelers. Restored to its 1930s-40s appearance, it looks almost exactly as it did when Basil 'Tubby' Ambler first pumped gas here nearly a century ago."
  },
  {
    "id": "H-054",
    "title": "Standard Oil Gas Station",
    "city": "Odell",
    "state": "IL",
    "lat": 41.0011,
    "lon": -88.5253,
    "cluster": "Illinois corridor",
    "siteType": "Historic gas station",
    "phenomenon": "A perfectly restored 1932 station that looks abandoned in time, frozen mid-Depression along a quiet stretch of the old highway.",
    "evidence": "A - Preserved historic structure",
    "detourMiles": "1",
    "priority": "Strong",
    "visit": "Quick photo stop",
    "access": "Free to view; open seasonally as a visitor center.",
    "official": "https://www.illinoisroute66.org/standard-oil-gas-station-odell",
    "folklore": "https://www.illinoisroute66.org/standard-oil-gas-station-odell",
    "history": "Built in 1932 in a style already outdated by the time it opened, this small station somehow survived nearly a century of highway changes and closures. Its restoration is considered one of the best-preserved examples of a Depression-era filling station left in the country."
  },
  {
    "id": "H-055",
    "title": "Polk-a-Dot Drive In",
    "city": "Braidwood",
    "state": "IL",
    "lat": 41.2683,
    "lon": -88.217,
    "cluster": "Illinois corridor",
    "siteType": "Roadside diner with statues",
    "phenomenon": "A collection of oddly life-like statues — Elvis, Marilyn Monroe, a superhero — stand watch outside a diner that never quite feels empty.",
    "evidence": "A - Directly observable oddity",
    "detourMiles": "1",
    "priority": "Strong",
    "visit": "Quick meal and photo stop",
    "access": "Open restaurant, normal business hours.",
    "official": "https://www.thepolkadotdrivein.com/",
    "folklore": "https://www.thepolkadotdrivein.com/",
    "history": "This 1950s-style drive-in has stood since the highway's golden age, and its collection of fiberglass celebrity statues has grown over the decades into one of the most photographed oddity stops on Route 66 — a diner that's part restaurant, part outdoor wax museum."
  },
  {
    "id": "H-056",
    "title": "David Davis Mansion",
    "city": "Bloomington",
    "state": "IL",
    "lat": 40.4931,
    "lon": -88.9612,
    "cluster": "Illinois corridor",
    "siteType": "Historic mansion",
    "phenomenon": "Staff and visitors describe a lingering presence tied to the judge who once owned this ornate Victorian home.",
    "evidence": "C - Local folklore",
    "detourMiles": "2",
    "priority": "Moderate",
    "visit": "Daytime guided tour",
    "access": "State historic site; check seasonal tour hours.",
    "official": "https://daviddavismansion.org/",
    "folklore": "https://daviddavismansion.org/",
    "history": "David Davis was Abraham Lincoln's close friend, campaign manager, and later a U.S. Supreme Court Justice. Lincoln himself is known to have visited this ornate 1872 Victorian mansion, one of the best-preserved homes of its era in the Midwest."
  },
  {
    "id": "H-057",
    "title": "Illinois State Fairgrounds",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.7681,
    "lon": -89.6259,
    "cluster": "Illinois corridor",
    "siteType": "State fairgrounds",
    "phenomenon": "Overnight fair workers over the decades have described unexplained sounds in the empty grandstand and old livestock barns after hours.",
    "evidence": "C - Worker folklore",
    "detourMiles": "3",
    "priority": "Moderate",
    "visit": "Exterior visit outside fair season",
    "access": "Public grounds; most buildings are closed outside the fair.",
    "official": "https://www.illinoisstatefair.info/",
    "folklore": "https://www.illinoisstatefair.info/",
    "history": "Illinois has held a state fair here since the 1890s, and the fairgrounds' oldest grandstand and barns have stood through well over a century of harvest seasons, livestock shows, and county fair traditions passed down across generations."
  },
  {
    "id": "H-058",
    "title": "Longbranch Coffeehouse Building",
    "city": "Bloomington",
    "state": "IL",
    "lat": 40.4842,
    "lon": -88.9937,
    "cluster": "Illinois corridor",
    "siteType": "Historic downtown building",
    "phenomenon": "Employees describe cold drafts and a shifting presence in the upper floors of this 19th-century downtown building.",
    "evidence": "C - Local business folklore",
    "detourMiles": "2",
    "priority": "Moderate",
    "visit": "Grab a coffee and ask about the stories",
    "access": "Open cafe, normal business hours.",
    "official": "https://www.downtownbloomington.org/",
    "folklore": "https://www.downtownbloomington.org/",
    "history": "Downtown Bloomington's 19th-century commercial buildings have housed dry goods stores, saloons, and offices across more than a century of Illinois small-town business history, and locals have passed down ghost stories about several of them for generations."
  },
  {
    "id": "H-059",
    "title": "Kankakee River State Park",
    "city": "Bourbonnais",
    "state": "IL",
    "lat": 41.1928,
    "lon": -87.9048,
    "cluster": "Illinois corridor",
    "siteType": "State park with old mill ruins",
    "phenomenon": "The ruins of an 1830s grist mill along the river have long collected local ghost stories from generations of area kids.",
    "evidence": "C - Local folklore",
    "detourMiles": "6",
    "priority": "Moderate",
    "visit": "Daylight hike to the mill ruins",
    "access": "State park, open daily.",
    "official": "https://www2.illinois.gov/dnr/parks/pages/kankakeeriver.aspx",
    "folklore": "https://www2.illinois.gov/dnr/parks/pages/kankakeeriver.aspx",
    "history": "The stone ruins of the old Bourbonnais Grist Mill still stand along the Kankakee River, remnants of an 1830s settlement that once ground grain for area farmers. The park today protects miles of limestone canyon and river bluff around those quiet ruins."
  },
  {
    "id": "H-060",
    "title": "Lincoln's Tomb War Memorials",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.8194,
    "lon": -89.6497,
    "cluster": "Illinois corridor",
    "siteType": "Cemetery memorial grounds",
    "phenomenon": "Beyond the tomb itself, the surrounding Oak Ridge Cemetery grounds have their own long list of reported unexplained lights and cold spots among the older sections.",
    "evidence": "C - Local folklore layered on a real cemetery",
    "detourMiles": "1",
    "priority": "Moderate",
    "visit": "Daylight walk through the grounds",
    "access": "Public cemetery, open daily, no fee.",
    "official": "https://oakridgecemeterylincolnstomb.org/",
    "folklore": "https://oakridgecemeterylincolnstomb.org/",
    "history": "Oak Ridge Cemetery is the second-most-visited cemetery in America after Arlington, almost entirely because of Lincoln's Tomb — but its older sections, some dating to the 1860s, hold thousands of other Springfield residents whose stories rarely get told."
  }
];
