window.JULES_STOPS = [
  {
    "id": "J-001",
    "title": "Kansas Speedway",
    "city": "Kansas City",
    "state": "KS",
    "lat": 39.1158,
    "lon": -94.8311,
    "icon": "flag",
    "emoji": "🏁",
    "theme": "Race Cars & Fast Machines",
    "why": "Real race cars, pit crews, giant grandstands, flags, engines, and the chance to see how a full-size speedway works.",
    "mission": "Choose one car to follow for five laps and count how many places it gains or loses.",
    "character": "Sonic-style speed mission",
    "energy": "Medium",
    "noise": "Very loud on race days; hearing protection is essential",
    "adultNotes": "Race access is event-based. Youth ticket offers vary by series. A non-race exterior stop is brief and much less rewarding.",
    "official": "https://www.kansasspeedway.com/"
  },
  {
    "id": "J-002",
    "title": "Children's Mercy Park",
    "city": "Kansas City",
    "state": "KS",
    "lat": 39.1219,
    "lon": -94.8232,
    "icon": "ball",
    "emoji": "⚽",
    "theme": "Sports & Stadiums",
    "why": "He can see the field from player level, look at the locker room, and experience a stadium built around fast action.",
    "mission": "Find the fastest path the ball could take from one goal to the other.",
    "character": "Sonic-style field-speed mission",
    "energy": "Medium",
    "noise": "Crowd noise during matches",
    "adultNotes": "Tours are not offered on every date and can involve substantial walking. A match may be more engaging than a formal tour at age five.",
    "official": "https://www.sportingkc.com/stadium/"
  },
  {
    "id": "J-003",
    "title": "CPKC Stadium",
    "city": "Kansas City",
    "state": "MO",
    "lat": 39.1169,
    "lon": -94.5786,
    "icon": "stadium",
    "emoji": "🏟️",
    "theme": "Sports & Stadiums",
    "why": "The stadium is compact, the players feel close, and the action is easy for a young child to follow.",
    "mission": "Count ten fast passes and shout 'turbo' when the ball changes direction quickly.",
    "character": "Sonic-style speed and teamwork",
    "energy": "Medium",
    "noise": "Crowd noise; sensory room available",
    "adultNotes": "Match tickets or an authorized event are required for seating areas. The stadium has family and sensory amenities.",
    "official": "https://cpkcstadium.com/"
  },
  {
    "id": "J-004",
    "title": "GEHA Field at Arrowhead Stadium",
    "city": "Kansas City",
    "state": "MO",
    "lat": 39.0489,
    "lon": -94.4839,
    "icon": "ball",
    "emoji": "🏈",
    "theme": "Sports & Stadiums",
    "why": "The field, helmets, tunnels, giant video boards, and player spaces make professional football feel enormous.",
    "mission": "Pretend to be a defender and choose the safest path to stop a runner from reaching the end zone.",
    "character": "Gekko-style strength mission",
    "energy": "Low to Medium",
    "noise": "Extremely loud during games",
    "adultNotes": "Tours are easier than games for seeing behind-the-scenes spaces. Game-day sound levels require child-sized hearing protection.",
    "official": "https://www.gehafieldatarrowhead.com/tours"
  },
  {
    "id": "J-005",
    "title": "Kauffman Stadium",
    "city": "Kansas City",
    "state": "MO",
    "lat": 39.0517,
    "lon": -94.4803,
    "icon": "ball",
    "emoji": "⚾",
    "theme": "Sports & Stadiums",
    "why": "Fountains, the crown scoreboard, baseball action, snacks, and space to watch the game in short bursts.",
    "mission": "Count every time the ball goes faster than a runner.",
    "character": "Sonic-style race between ball and player",
    "energy": "Low",
    "noise": "Moderate crowd noise",
    "adultNotes": "Tours can involve about a mile of walking. A family section or shorter game visit may work better at age five.",
    "official": "https://www.mlb.com/royals/ballpark/tours"
  },
  {
    "id": "J-006",
    "title": "Science City",
    "city": "Kansas City",
    "state": "MO",
    "lat": 39.0853,
    "lon": -94.5858,
    "icon": "ring",
    "emoji": "💍💨",
    "theme": "Sonic-Style Speed Challenges",
    "why": "He can climb, race, lift, slide, build, and test machines instead of only looking at exhibits.",
    "mission": "Find the exhibit that makes something move the fastest without using a motor.",
    "character": "Sonic speed plus Gekko strength",
    "energy": "High",
    "noise": "Busy indoor environment",
    "adultNotes": "One of the best all-weather stops. Build in snack and quiet breaks because it can be stimulating.",
    "official": "https://sciencecity.unionstation.org/"
  },
  {
    "id": "J-007",
    "title": "LEGOLAND Discovery Center Kansas City",
    "city": "Kansas City",
    "state": "MO",
    "lat": 39.0811,
    "lon": -94.5818,
    "icon": "flag",
    "emoji": "🏎️",
    "theme": "Race Cars & Fast Machines",
    "why": "He can build a small car, change the wheels or shape, and race it against other designs.",
    "mission": "Build three cars: fastest, strongest, and funniest. Race all three.",
    "character": "Sonic speed and Gekko strength",
    "energy": "Medium",
    "noise": "Busy indoor attraction",
    "adultNotes": "Timed tickets are recommended. Adults generally must be accompanied by a child.",
    "official": "https://www.legolanddiscoverycenter.com/kansas-city/"
  },
  {
    "id": "J-008",
    "title": "Kansas City Zoo and Aquarium",
    "city": "Kansas City",
    "state": "MO",
    "lat": 39.0068,
    "lon": -94.5293,
    "icon": "hero",
    "emoji": "🦎🛡️",
    "theme": "Gekko Hero & Animal Missions",
    "why": "Animals that climb, hide, swim, stick, leap, or use camouflage create natural superhero comparisons.",
    "mission": "Find one animal that is strong like Gekko and one that is fast like Sonic.",
    "character": "Gekko animal-power mission",
    "energy": "Medium",
    "noise": "Outdoor walking; aquarium can be dark",
    "adultNotes": "The property is large. Choose a few priority animals and use transportation options when available.",
    "official": "https://kansascityzoo.org/"
  },
  {
    "id": "J-009",
    "title": "Faurot Field at Memorial Stadium",
    "city": "Columbia",
    "state": "MO",
    "lat": 38.9358,
    "lon": -92.3333,
    "icon": "stadium",
    "emoji": "🏟️",
    "theme": "Sports & Stadiums",
    "why": "The giant rock M, football field, team colors, and stadium scale make an easy sports photo stop.",
    "mission": "Find the biggest letter M and make a strong Gekko pose beside it.",
    "character": "Gekko strength mission",
    "energy": "Low",
    "noise": "Very loud on game days",
    "adultNotes": "Interior access is event-dependent. A public campus walk works when no game is scheduled.",
    "official": "https://mutigers.com/facilities/memorial-stadium-faurot-field/1"
  },
  {
    "id": "J-010",
    "title": "Big Joel's Safari",
    "city": "Wright City",
    "state": "MO",
    "lat": 38.824,
    "lon": -91.025,
    "icon": "paw",
    "emoji": "🐾",
    "theme": "Gekko Hero & Animal Missions",
    "why": "More than 60 animal species and close encounters make it easy to compare animal powers.",
    "mission": "Choose the animal with the best superhero power and name that power.",
    "character": "Gekko animal-power mission",
    "energy": "Medium",
    "noise": "Outdoor smells, animal sounds, feeding activity",
    "adultNotes": "Open seasonally with posted daily hours. Follow all feeding and touching rules.",
    "official": "https://www.bigjoelsafari.com/"
  },
  {
    "id": "J-011",
    "title": "Busch Stadium",
    "city": "St. Louis",
    "state": "MO",
    "lat": 38.6226,
    "lon": -90.1928,
    "icon": "stadium",
    "emoji": "🏟️⚾",
    "theme": "Sports & Stadiums",
    "why": "A major baseball stadium with bright team colors, player spaces, bats, balls, and a skyline view.",
    "mission": "Pick one player and watch only that player for a full inning.",
    "character": "Sports hero mission",
    "energy": "Low",
    "noise": "Moderate to loud during games",
    "adultNotes": "Tours and games are ticketed. Plan around nap time and avoid expecting a five-year-old to remain seated for nine innings.",
    "official": "https://www.mlb.com/cardinals/ballpark/tours"
  },
  {
    "id": "J-012",
    "title": "Enterprise Center",
    "city": "St. Louis",
    "state": "MO",
    "lat": 38.6268,
    "lon": -90.2026,
    "icon": "ball",
    "emoji": "🏒",
    "theme": "Sports & Stadiums",
    "why": "Hockey is fast, the players wear superhero-like gear, and the puck changes direction constantly.",
    "mission": "Count five times a player changes direction without falling.",
    "character": "Sonic speed on ice",
    "energy": "Low",
    "noise": "Loud horn, music, and crowd",
    "adultNotes": "Event-based access. Hearing protection and aisle seats can help a young child.",
    "official": "https://www.enterprisecenter.com/"
  },
  {
    "id": "J-013",
    "title": "Energizer Park",
    "city": "St. Louis",
    "state": "MO",
    "lat": 38.6312,
    "lon": -90.2104,
    "icon": "ring",
    "emoji": "💍💨",
    "theme": "Sports & Stadiums",
    "why": "Fast soccer action, strong colors, supporter songs, and a modern stadium close to the field.",
    "mission": "Spot ten circles that look like Sonic rings in the stadium or district.",
    "character": "Sonic ring hunt",
    "energy": "Medium",
    "noise": "Supporter section can be very loud",
    "adultNotes": "Match access is ticketed. Use quieter seating away from supporter sections for a five-year-old.",
    "official": "https://www.stlcitysc.com/stadium/"
  },
  {
    "id": "J-014",
    "title": "World Wide Technology Raceway",
    "city": "Madison",
    "state": "IL",
    "lat": 38.6511,
    "lon": -90.136,
    "icon": "flag",
    "emoji": "🏁",
    "theme": "Race Cars & Fast Machines",
    "why": "The site hosts different kinds of racing, allowing him to compare oval cars, dragsters, and other machines.",
    "mission": "Choose which race car would beat Sonic in a straight line and which would win on a turn.",
    "character": "Ultimate Sonic speed mission",
    "energy": "Medium",
    "noise": "Extremely loud; hearing protection required",
    "adultNotes": "Event schedule determines access. Some motorsports events run late and may not fit a five-year-old's routine.",
    "official": "https://wwtraceway.com/"
  },
  {
    "id": "J-015",
    "title": "National Museum of Transportation",
    "city": "Kirkwood",
    "state": "MO",
    "lat": 38.571,
    "lon": -90.4622,
    "icon": "machine",
    "emoji": "🚂",
    "theme": "Race Cars & Fast Machines",
    "why": "Full-size locomotives, automobiles, aircraft, and giant machines allow him to compare speed, strength, and size.",
    "mission": "Find the biggest machine, the fastest-looking machine, and the machine Gekko could climb.",
    "character": "Sonic speed plus Gekko climbing",
    "energy": "Medium",
    "noise": "Mostly calm; outdoor walking",
    "adultNotes": "Large site with indoor and outdoor areas. Check miniature train operating times.",
    "official": "https://tnmot.org/"
  },
  {
    "id": "J-016",
    "title": "The Magic House",
    "city": "Kirkwood",
    "state": "MO",
    "lat": 38.5789,
    "lon": -90.4075,
    "icon": "hero",
    "emoji": "🛡️⭐",
    "theme": "Sonic-Style Speed Challenges",
    "why": "A five-year-old can move, build, pretend, solve problems, and try sports-themed activities at his own pace.",
    "mission": "Complete three hero jobs: build something, help someone, and finish one movement challenge.",
    "character": "Gekko hero mission",
    "energy": "High",
    "noise": "Busy and interactive",
    "adultNotes": "Excellent age fit. Set a meeting point and expect the child to move quickly between exhibits.",
    "official": "https://www.magichouse.org/"
  },
  {
    "id": "J-017",
    "title": "St. Louis Aquarium",
    "city": "St. Louis",
    "state": "MO",
    "lat": 38.6294,
    "lon": -90.2073,
    "icon": "hero",
    "emoji": "🦎🛡️",
    "theme": "Gekko Hero & Animal Missions",
    "why": "Underwater tunnels, animals that hide, powerful swimmers, and creatures that look like superheroes.",
    "mission": "Find the best underwater camouflage and the fastest swimmer.",
    "character": "Gekko underwater mission",
    "energy": "Low",
    "noise": "Dark lighting and enclosed habitats",
    "adultNotes": "Timed admission is recommended. Union Station has additional attractions that can extend the stop.",
    "official": "https://www.stlouisaquarium.com/"
  },
  {
    "id": "J-018",
    "title": "Robin Roberts Stadium",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.8314,
    "lon": -89.653,
    "icon": "ball",
    "emoji": "⚾",
    "theme": "Sports & Stadiums",
    "why": "A smaller stadium can be easier for a young child because the action and players feel closer.",
    "mission": "Count how many throws happen before the ball returns to the pitcher.",
    "character": "Sports speed mission",
    "energy": "Low",
    "noise": "Moderate",
    "adultNotes": "Event-based access. Check the 2026 game calendar before adding it to a travel day.",
    "official": "https://www.springfieldparks.org/facilities/baseball/robin-roberts-stadium/"
  },
  {
    "id": "J-019",
    "title": "Kidzeum of Health and Science",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.8018,
    "lon": -89.648,
    "icon": "hero",
    "emoji": "💪⭐",
    "theme": "Gekko Hero & Animal Missions",
    "why": "He can learn what muscles, movement, food, and healthy bodies do through play.",
    "mission": "Find which body part helps Gekko climb and which helps Sonic run.",
    "character": "Gekko muscles and Sonic legs",
    "energy": "Medium",
    "noise": "Interactive indoor space",
    "adultNotes": "Strong fit for preschool and early elementary ages. Check daily hours before the downtown stop.",
    "official": "https://kidzeum.org/"
  },
  {
    "id": "J-020",
    "title": "Henson Robinson Zoo",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.7334,
    "lon": -89.5867,
    "icon": "paw",
    "emoji": "🐾",
    "theme": "Gekko Hero & Animal Missions",
    "why": "A smaller zoo makes it easier to finish an animal mission without exhausting the entire family.",
    "mission": "Find an animal that climbs, one that runs, and one that hides.",
    "character": "Gekko camouflage mission",
    "energy": "Medium",
    "noise": "Outdoor walking",
    "adultNotes": "Seasonal operations and weather matter. The zoo reopened for normal hours in June 2026.",
    "official": "https://www.springfieldparks.org/locations/3/henson-robinson-zoo/springfield/facility-details"
  },
  {
    "id": "J-021",
    "title": "Knight's Action Park",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.7354,
    "lon": -89.7132,
    "icon": "ring",
    "emoji": "💍💨",
    "theme": "Sonic-Style Speed Challenges",
    "why": "Kiddie water areas, family attractions, and movement challenges offer a safer version of a speed-filled amusement stop.",
    "mission": "Complete one fast challenge and one brave-but-slow challenge.",
    "character": "Sonic speed with Gekko courage",
    "energy": "High",
    "noise": "Water, crowds, and ride noise",
    "adultNotes": "Seasonal. Height restrictions apply to many attractions, but shallow and zero-depth areas are available for younger guests.",
    "official": "https://www.knightsactionpark.com/"
  },
  {
    "id": "J-022",
    "title": "Chicagoland Speedway",
    "city": "Joliet",
    "state": "IL",
    "lat": 41.4736,
    "lon": -88.0575,
    "icon": "flag",
    "emoji": "🏁",
    "theme": "Race Cars & Fast Machines",
    "why": "The 1.5-mile oval returned to the NASCAR schedule in 2026, giving him another major race venue to compare with Kansas Speedway.",
    "mission": "Decide which track looks faster: Kansas or Chicagoland, and explain why.",
    "character": "Sonic track comparison",
    "energy": "Medium",
    "noise": "Extremely loud",
    "adultNotes": "The 2026 NASCAR weekend occurred July 3-5. Future access depends on the event calendar. Hearing protection is mandatory for a young child.",
    "official": "https://www.chicagolandspeedway.com/"
  },
  {
    "id": "J-023",
    "title": "Route 66 Raceway",
    "city": "Joliet",
    "state": "IL",
    "lat": 41.4705,
    "lon": -88.0672,
    "icon": "flag",
    "emoji": "🏎️💨",
    "theme": "Race Cars & Fast Machines",
    "why": "Drag racing is simple to understand: two vehicles start together and the first to the finish wins.",
    "mission": "Pick a winner before each race based only on the car's shape and sound.",
    "character": "Straight-line Sonic speed",
    "energy": "Low",
    "noise": "Extremely loud and sudden",
    "adultNotes": "Event-only attraction. Drag racing noise can be startling even with hearing protection.",
    "official": "https://www.route66raceway.com/"
  },
  {
    "id": "J-024",
    "title": "Duly Health and Care Field, Joliet Slammers",
    "city": "Joliet",
    "state": "IL",
    "lat": 41.5258,
    "lon": -88.078,
    "icon": "ball",
    "emoji": "⚾🎉",
    "theme": "Sports & Stadiums",
    "why": "Minor league games add mascots, silly promotions, close seats, and shorter attention-friendly entertainment.",
    "mission": "Choose the funniest between-inning game and invent a new one.",
    "character": "Playful sports hero mission",
    "energy": "Low",
    "noise": "Moderate",
    "adultNotes": "Check the promotional schedule. Evening games may run past a five-year-old's bedtime.",
    "official": "https://jolietslammers.com/"
  },
  {
    "id": "J-025",
    "title": "Route 66 Welcome Center at Joliet Area Historical Museum",
    "city": "Joliet",
    "state": "IL",
    "lat": 41.5255,
    "lon": -88.081,
    "icon": "hero",
    "emoji": "🛡️",
    "theme": "Race Cars & Fast Machines",
    "why": "Road signs, cars, maps, and Route 66 imagery connect naturally to a child who likes racing and road-trip stories.",
    "mission": "Find three road signs that could belong in a Sonic racing level.",
    "character": "Sonic road-course mission",
    "energy": "Low",
    "noise": "Quiet indoor museum",
    "adultNotes": "Good short reset stop near the ballpark. Check current museum and welcome-center hours.",
    "official": "https://www.jolietmuseum.org/"
  },
  {
    "id": "J-026",
    "title": "U.S. Steel Yard, Gary SouthShore RailCats",
    "city": "Gary",
    "state": "IN",
    "lat": 41.6029,
    "lon": -87.3376,
    "icon": "machine",
    "emoji": "🚂⚾",
    "theme": "Sports & Stadiums",
    "why": "Baseball, a train-themed team name, mascots, and between-inning entertainment create several interests in one stop.",
    "mission": "Find every train reference in the team's name, logo, stadium, or sounds.",
    "character": "Fast train mission",
    "energy": "Low",
    "noise": "Moderate; fireworks on some nights",
    "adultNotes": "Choose a game without postgame fireworks if sudden noise is a concern.",
    "official": "https://railcatsbaseball.com/"
  },
  {
    "id": "J-027",
    "title": "Indiana Dunes National Park Visitor Center and West Beach",
    "city": "Porter",
    "state": "IN",
    "lat": 41.6331,
    "lon": -87.0544,
    "icon": "hero",
    "emoji": "🦎🛡️",
    "theme": "Gekko Hero & Animal Missions",
    "why": "Sand hills, animal tracks, hiding places, and climbing challenges make the landscape feel like a superhero level.",
    "mission": "Find tracks, climb one safe dune, and identify the best camouflage color.",
    "character": "Gekko climbing and camouflage",
    "energy": "High",
    "noise": "Sun, sand, wind, and heat",
    "adultNotes": "Choose a short, age-appropriate trail. Sand walking is more tiring than normal walking.",
    "official": "https://www.nps.gov/indu/index.htm"
  },
  {
    "id": "J-028",
    "title": "Washington Park Zoo",
    "city": "Michigan City",
    "state": "IN",
    "lat": 41.724,
    "lon": -86.8895,
    "icon": "hero",
    "emoji": "🦎🛡️",
    "theme": "Gekko Hero & Animal Missions",
    "why": "Animals, a hillside setting, and the chance to climb to a high view make it feel like a Gekko patrol.",
    "mission": "Find the animal that would be best at climbing the zoo's hill.",
    "character": "Gekko climbing mission",
    "energy": "Medium",
    "noise": "Outdoor hills and walking",
    "adultNotes": "Seasonal, with hills and stairs. Confirm tower and zoo access before arrival.",
    "official": "https://www.washingtonparkzoo.com/"
  },
  {
    "id": "J-029",
    "title": "Studebaker National Museum",
    "city": "South Bend",
    "state": "IN",
    "lat": 41.6749,
    "lon": -86.2617,
    "icon": "machine",
    "emoji": "🚗",
    "theme": "Race Cars & Fast Machines",
    "why": "Historic cars, unusual shapes, shiny details, and vehicles from different eras create an easy visual experience.",
    "mission": "Choose the car Sonic would drive and the car Gekko would drive.",
    "character": "Character vehicle mission",
    "energy": "Low",
    "noise": "Quiet museum",
    "adultNotes": "Excellent indoor stop. Keep the mission visual because long text panels may not hold a five-year-old's attention.",
    "official": "https://www.studebakermuseum.org/"
  },
  {
    "id": "J-030",
    "title": "Four Winds Field, South Bend Cubs",
    "city": "South Bend",
    "state": "IN",
    "lat": 41.6709,
    "lon": -86.2557,
    "icon": "ball",
    "emoji": "⚾🎉",
    "theme": "Sports & Stadiums",
    "why": "Close seats, a mascot, promotions, and a family-oriented minor league environment.",
    "mission": "Race the runner from home plate to first base using two fingers on the scorecard.",
    "character": "Sonic base-running race",
    "energy": "Low",
    "noise": "Moderate",
    "adultNotes": "Choose an early game when available. The team store can provide a shorter stop if no game fits.",
    "official": "https://www.milb.com/south-bend"
  },
  {
    "id": "J-031",
    "title": "Notre Dame Stadium",
    "city": "Notre Dame",
    "state": "IN",
    "lat": 41.6984,
    "lon": -86.2339,
    "icon": "stadium",
    "emoji": "🏟️🏈",
    "theme": "Sports & Stadiums",
    "why": "A huge college stadium, player statues, helmets, and open campus spaces make a strong visual stop.",
    "mission": "Find three places a superhero could stand to watch the whole field.",
    "character": "Gekko lookout mission",
    "energy": "Medium",
    "noise": "Quiet outside events; very loud on game days",
    "adultNotes": "Interior access is not guaranteed without a tour. A short campus walk may be enough at age five.",
    "official": "https://tour.nd.edu/locations/notre-dame-stadium/"
  },
  {
    "id": "J-032",
    "title": "Air Zoo Aerospace and Science Museum",
    "city": "Portage",
    "state": "MI",
    "lat": 42.2354,
    "lon": -85.552,
    "icon": "machine",
    "emoji": "✈️",
    "theme": "Sonic-Style Speed Challenges",
    "why": "Aircraft, indoor amusement rides, flight displays, and big machines make this one of the strongest child-focused stops.",
    "mission": "Choose the fastest-looking airplane and explain which part makes it look fast.",
    "character": "Sonic flight-speed mission",
    "energy": "Medium",
    "noise": "Large indoor space; ride motion",
    "adultNotes": "Ride and simulator height restrictions vary. General exhibits still provide excellent value if he cannot ride everything.",
    "official": "https://www.airzoo.org/"
  },
  {
    "id": "J-033",
    "title": "Gilmore Car Museum",
    "city": "Hickory Corners",
    "state": "MI",
    "lat": 42.4424,
    "lon": -85.4203,
    "icon": "flag",
    "emoji": "🏎️",
    "theme": "Race Cars & Fast Machines",
    "why": "A campus full of cars lets him compare racers, classics, trucks, colors, shapes, and old service stations.",
    "mission": "Award three trophies: fastest-looking, strongest-looking, and most like a cartoon car.",
    "character": "Sonic speed and vehicle-design mission",
    "energy": "Medium",
    "noise": "Mostly quiet; considerable walking",
    "adultNotes": "This is a meaningful detour northeast of Kalamazoo. It deserves at least two hours.",
    "official": "https://gilmorecarmuseum.org/"
  },
  {
    "id": "J-034",
    "title": "Impression 5 Science Center",
    "city": "Lansing",
    "state": "MI",
    "lat": 42.7348,
    "lon": -84.5494,
    "icon": "hero",
    "emoji": "🛡️⭐",
    "theme": "Gekko Hero & Animal Missions",
    "why": "The exhibits focus on touching, moving, building, testing, and using all five senses.",
    "mission": "Complete one strength test, one speed test, and one camouflage or nature test.",
    "character": "Gekko hero-training center",
    "energy": "High",
    "noise": "Interactive and busy; young-child area available",
    "adultNotes": "A strong all-weather stop. Construction may affect downtown access, so check directions before arrival.",
    "official": "https://impression5.org/"
  },
  {
    "id": "J-035",
    "title": "R.E. Olds Transportation Museum",
    "city": "Lansing",
    "state": "MI",
    "lat": 42.7333,
    "lon": -84.5507,
    "icon": "machine",
    "emoji": "🚗",
    "theme": "Race Cars & Fast Machines",
    "why": "Cars, engines, signs, and Lansing's automotive history are displayed next door to Impression 5.",
    "mission": "Find the oldest car and the car with the biggest front grille.",
    "character": "Vehicle detective mission",
    "energy": "Low",
    "noise": "Quiet museum",
    "adultNotes": "Pair it with Impression 5. The museum is less interactive, so use a short visual scavenger hunt.",
    "official": "https://www.reoldsmuseum.org/"
  },
  {
    "id": "J-036",
    "title": "Jackson Field, Lansing Lugnuts",
    "city": "Lansing",
    "state": "MI",
    "lat": 42.7347,
    "lon": -84.5468,
    "icon": "ball",
    "emoji": "⚾🎉",
    "theme": "Sports & Stadiums",
    "why": "The funny team name, mascot, close views, and downtown stadium make baseball approachable.",
    "mission": "Find five things shaped like circles or rings around the stadium.",
    "character": "Sonic ring hunt",
    "energy": "Low",
    "noise": "Moderate",
    "adultNotes": "Select an early game or visit the team store during public hours for a shorter experience.",
    "official": "https://www.milb.com/lansing"
  },
  {
    "id": "J-037",
    "title": "Call of the Wild Museum",
    "city": "Gaylord",
    "state": "MI",
    "lat": 45.0234,
    "lon": -84.6783,
    "icon": "paw",
    "emoji": "🐾",
    "theme": "Gekko Hero & Animal Missions",
    "why": "Large animal displays make it easy to compare claws, camouflage, speed, teeth, and strength.",
    "mission": "Build a superhero using one power from three different northern animals.",
    "character": "Gekko animal-power mission",
    "energy": "Low",
    "noise": "Quiet indoor displays; taxidermy animals",
    "adultNotes": "Preview whether realistic taxidermy displays will appeal to him. The stop is compact and easy to shorten.",
    "official": "https://callofthewildgaylord.com/"
  },
  {
    "id": "J-038",
    "title": "Big Bear Adventures Outdoor Fun Center",
    "city": "Indian River",
    "state": "MI",
    "lat": 45.3743,
    "lon": -84.6293,
    "icon": "ring",
    "emoji": "💍💨",
    "theme": "Sonic-Style Speed Challenges",
    "why": "Adventure golf, bumper boats, and challenge elements create a playful speed and skill break.",
    "mission": "Complete one hole using the fewest hits and one using the funniest safe strategy.",
    "character": "Sonic course mission",
    "energy": "Medium",
    "noise": "Outdoor weather and water activity",
    "adultNotes": "Activity availability and minimum heights vary. The adventure golf option is the most reliable age-five fit.",
    "official": "https://bigbearadventures.com/"
  },
  {
    "id": "J-039",
    "title": "Icebreaker Mackinaw Maritime Museum",
    "city": "Mackinaw City",
    "state": "MI",
    "lat": 45.7824,
    "lon": -84.7277,
    "icon": "machine",
    "emoji": "🚢🧊",
    "theme": "Race Cars & Fast Machines",
    "why": "The giant ship, engines, ladders, wheelhouse, and icebreaking mission feel like a real superhero vehicle.",
    "mission": "Find five things the ship needs to be stronger than ice.",
    "character": "Gekko super-strength vehicle",
    "energy": "High",
    "noise": "Steep ladders, narrow passages, ship motion possible",
    "adultNotes": "Close supervision is required. The ship has steep ladders and limited accessibility.",
    "official": "https://themackinaw.org/"
  },
  {
    "id": "J-040",
    "title": "Bois Blanc Island Superhero Speed and Camouflage Mission",
    "city": "Bois Blanc Island",
    "state": "MI",
    "lat": 45.7465,
    "lon": -84.496,
    "icon": "hero",
    "emoji": "🏝️🦸",
    "theme": "Gekko Hero & Animal Missions",
    "why": "The island becomes one large level with gravel roads, boats, beaches, hiding places, animals, and family movement.",
    "mission": "Complete four missions: find a blue Sonic view, a green Gekko hiding place, a fast machine, and a strong natural object.",
    "character": "Final Sonic and Gekko team mission",
    "energy": "Medium",
    "noise": "Wind, insects, gravel roads, ferry sounds",
    "adultNotes": "Use only public roads and access points. Keep the route short for a five-year-old, and plan around ferry times, weather, insects, food, water, and limited services.",
    "official": "https://www.boisblanctownship.org/"
  }
];
