window.KATRINA_STOPS = [
  {
    "id": "K-001",
    "title": "Rainy Day Books",
    "city": "Fairway",
    "state": "KS",
    "lat": 39.0335,
    "lon": -94.6162,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "A long-running independent bookstore where Katrina can choose the book that becomes her personal companion for the drive.",
    "suggestedBook": "Katrina chooses one middle-grade mystery or adventure",
    "detourMiles": "7",
    "stopMinutes": "45",
    "visitStyle": "Road-trip book selection",
    "experience": "Staff recommendations, new releases, middle-grade shelves, and the responsibility of selecting one book within a set budget.",
    "why": "The trip begins with her making a choice that belongs only to her, rather than inheriting a sister's theme.",
    "quest": "Choose a book without reading the back cover first. Make three predictions from the title, cover, and first page.",
    "sisterCrossover": "She may ask Elsie and Emma to each predict whether she will like her choice.",
    "access": "Independent bookstore hours can change for author events. Verify the current schedule before departure.",
    "official": "https://www.rainydaybooks.com/",
    "learnMore": "https://www.rainydaybooks.com/about-us"
  },
  {
    "id": "K-002",
    "title": "The Rabbit hOle",
    "city": "North Kansas City",
    "state": "MO",
    "lat": 39.1357,
    "lon": -94.5653,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "A museum where scenes from children's books become full-scale spaces that visitors can enter, touch, and explore.",
    "suggestedBook": "The Three Robbers",
    "detourMiles": "5",
    "stopMinutes": "120",
    "visitStyle": "Immersive literature visit",
    "experience": "Large-scale book environments, illustration, sculpture, sound, hidden details, and interactive storytelling.",
    "why": "It lets her enjoy younger-sister play while analyzing the space like an older reader.",
    "quest": "Find one detail that was not necessary to tell the story but makes the storyworld feel real.",
    "sisterCrossover": "Elsie can find the strangest scene, while Emma can choose the best color or design.",
    "access": "Timed admission is recommended. Children under 16 must visit with an adult. Current exhibitions can change.",
    "official": "https://www.rabbitholekc.org/",
    "learnMore": "https://www.rabbitholekc.org/visit"
  },
  {
    "id": "K-003",
    "title": "Kansas City Public Library Central Library and Community Bookshelf",
    "city": "Kansas City",
    "state": "MO",
    "lat": 39.1026,
    "lon": -94.5846,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "The former bank is now a dramatic library, while the nearby parking structure is wrapped in enormous book spines selected by the community.",
    "suggestedBook": "Escape from Mr. Lemoncello's Library",
    "detourMiles": "1",
    "stopMinutes": "75",
    "visitStyle": "Library architecture scavenger hunt",
    "experience": "A vault, historic interiors, reading rooms, public art, and a streetscape that turns favorite books into architecture.",
    "why": "The location feels like a real puzzle library without becoming childish.",
    "quest": "Choose five giant book spines and invent a secret clue that links all five titles.",
    "sisterCrossover": "Each sister chooses one book spine for a family reading list.",
    "access": "Library areas may close for events. Use public library and sidewalk spaces only.",
    "official": "https://kclibrary.org/locations/central",
    "learnMore": "https://kclibrary.org/community-bookshelf"
  },
  {
    "id": "K-004",
    "title": "Negro Leagues Baseball Museum",
    "city": "Kansas City",
    "state": "MO",
    "lat": 39.0914,
    "lon": -94.5636,
    "icon": "fashion",
    "interest": "Sports & Sister Crossover",
    "storyConnection": "The museum tells the stories of players and teams through uniforms, photographs, statistics, artifacts, and recreated baseball environments.",
    "suggestedBook": "We Are the Ship",
    "detourMiles": "2",
    "stopMinutes": "90",
    "visitStyle": "Story-led museum visit",
    "experience": "Player biographies, team identities, equipment, the Field of Legends, and the history of athletes who created opportunity despite exclusion.",
    "why": "It makes sports feel like a collection of determined individual stories rather than only scores and standings.",
    "quest": "Choose one player and write a four-sentence book-jacket description of that person's life.",
    "sisterCrossover": "Emma can study uniforms, while Katrina focuses on the person inside the uniform.",
    "access": "Ticketed museum. Allow enough time to read exhibit labels rather than rushing through the displays.",
    "official": "https://www.nlbm.com/",
    "learnMore": "https://www.nlbm.com/about-us/"
  },
  {
    "id": "K-005",
    "title": "The National Museum of Toys and Miniatures",
    "city": "Kansas City",
    "state": "MO",
    "lat": 39.0347,
    "lon": -94.5804,
    "icon": "ghost",
    "interest": "Mystery & Unusual History",
    "storyConnection": "Tiny rooms, objects, toys, and highly detailed miniature worlds resemble the secret-scale adventures found in middle-grade fantasy.",
    "suggestedBook": "The Doll People",
    "detourMiles": "5",
    "stopMinutes": "90",
    "visitStyle": "Miniature detail hunt",
    "experience": "Fine-scale rooms, historic toys, mechanical objects, dollhouses, and craftsmanship that rewards close observation.",
    "why": "It combines the imaginative play she shares with Emma with the hidden-detail mysteries Elsie enjoys.",
    "quest": "Find the smallest object that could become the most important clue in a mystery.",
    "sisterCrossover": "Each sister selects a miniature room and explains what story happens there after closing.",
    "access": "Ticketed museum. Check current gallery closures and photography policies.",
    "official": "https://toyandminiaturemuseum.org/",
    "learnMore": "https://toyandminiaturemuseum.org/about/"
  },
  {
    "id": "K-006",
    "title": "Science City at Union Station",
    "city": "Kansas City",
    "state": "MO",
    "lat": 39.0853,
    "lon": -94.5858,
    "icon": "book",
    "interest": "Science & Weather",
    "storyConnection": "Interactive experiments can be paired with a story about a child using science to solve a difficult problem.",
    "suggestedBook": "The Fourteenth Goldfish",
    "detourMiles": "1",
    "stopMinutes": "120",
    "visitStyle": "Hands-on experiment challenge",
    "experience": "More than 200 interactive experiences involving physics, engineering, nature, motion, and creative problem solving.",
    "why": "She can act, test, and compete without the stop depending on whether karate remains important to her.",
    "quest": "Pick one experiment, change one variable, and explain why the result changed.",
    "sisterCrossover": "Emma can connect the exhibits to weather, while Elsie finds the experiment with the strangest result.",
    "access": "Admission and hours may vary with Union Station events. Reserve extra time during weekends and school breaks.",
    "official": "https://sciencecity.unionstation.org/",
    "learnMore": "https://sciencecity.unionstation.org/about-science-city/"
  },
  {
    "id": "K-007",
    "title": "Hallmark Kaleidoscope",
    "city": "Kansas City",
    "state": "MO",
    "lat": 39.0803,
    "lon": -94.5805,
    "icon": "fashion",
    "interest": "Creative & Sister Crossover",
    "storyConnection": "A free creative studio where paper, color, shapes, and discarded Hallmark materials can become characters, scenes, props, or book covers.",
    "suggestedBook": "The Cardboard Kingdom",
    "detourMiles": "1",
    "stopMinutes": "50",
    "visitStyle": "Create a road-trip story artifact",
    "experience": "Open-ended art stations, unusual paper materials, machines, and the chance to build without following one prescribed craft.",
    "why": "She can make something sophisticated or silly depending on her mood, without being assigned a younger child's craft.",
    "quest": "Create a cover for a book called Katrina and the Road to the Island.",
    "sisterCrossover": "Each sister contributes one symbol that must appear on the cover.",
    "access": "Admission is free, but sessions and capacity can be limited. Check reservation and arrival instructions.",
    "official": "https://www.hallmarkkaleidoscope.com/",
    "learnMore": "https://www.hallmarkkaleidoscope.com/plan-your-visit"
  },
  {
    "id": "K-008",
    "title": "Daniel Boone Regional Library, Columbia Public Library",
    "city": "Columbia",
    "state": "MO",
    "lat": 38.9531,
    "lon": -92.3437,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "A major regional library that can become a controlled book scavenger hunt and a quiet reset during the drive.",
    "suggestedBook": "Book Scavenger",
    "detourMiles": "1",
    "stopMinutes": "45",
    "visitStyle": "Library scavenger challenge",
    "experience": "Children's and teen areas, displays, local recommendations, public art, and the logic of how a large library organizes information.",
    "why": "It makes reading active by turning classification and shelves into a puzzle.",
    "quest": "Find a book using only three clues provided by an adult, without using the title in the search.",
    "sisterCrossover": "Elsie supplies a spooky clue, while Emma supplies a sports or fashion clue.",
    "access": "Use normal public library areas and keep the challenge quiet and respectful.",
    "official": "https://www.dbrl.org/locations/columbia-public-library",
    "learnMore": "https://www.dbrl.org/"
  },
  {
    "id": "K-009",
    "title": "State Historical Society of Missouri, Center for Missouri Studies",
    "city": "Columbia",
    "state": "MO",
    "lat": 38.9452,
    "lon": -92.3294,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "The research center preserves Laura Ingalls Wilder manuscripts, correspondence, diaries, and other material connected to the creation of the Little House books.",
    "suggestedBook": "The Long Winter",
    "detourMiles": "2",
    "stopMinutes": "75",
    "visitStyle": "Gallery visit and prearranged archive introduction",
    "experience": "Original-source history, handwritten material, galleries, research spaces, and the difference between a real life and its published version.",
    "why": "It reveals that books begin as drafts, notes, memories, and choices rather than appearing as finished stories.",
    "quest": "Compare one historical source with a scene from a book. Identify what an author might simplify, combine, or leave out.",
    "sisterCrossover": "Emma can focus on winter weather, while Elsie looks for the hardest moment in the story.",
    "access": "Gallery access is public, but archival materials usually require advance arrangements and may not be displayed.",
    "official": "https://shsmo.org/visit/center-for-missouri-studies",
    "learnMore": "https://collections.shsmo.org/manuscripts/columbia/c3633"
  },
  {
    "id": "K-010",
    "title": "Stephens College Costume Museum and Research Library",
    "city": "Columbia",
    "state": "MO",
    "lat": 38.952,
    "lon": -92.3255,
    "icon": "fashion",
    "interest": "Creative & Sister Crossover",
    "storyConnection": "A collection of more than 13,000 garments and accessories can be used to investigate how clothing reveals a character's time, status, work, and personality.",
    "suggestedBook": "The Fashion Disaster That Changed My Life",
    "detourMiles": "2",
    "stopMinutes": "60",
    "visitStyle": "Current exhibition or scheduled tour",
    "experience": "Historic silhouettes, textiles, accessories, designer work, conservation, and the practical construction behind clothing.",
    "why": "She can share Emma's fashion interest while treating garments as clues about fictional and real people.",
    "quest": "Choose one garment and invent the character who would wear it, including a secret the clothing helps hide.",
    "sisterCrossover": "Emma evaluates the design, while Katrina creates the wearer and story.",
    "access": "Public exhibits rotate. Collection storage and research access are limited, so confirm what will be visible.",
    "official": "https://stephens.edu/costume-museum-research-library/",
    "learnMore": "https://stephens.edu/program/fashion-apparel-studies/"
  },
  {
    "id": "K-011",
    "title": "Mark Twain Boyhood Home and Museum",
    "city": "Hannibal",
    "state": "MO",
    "lat": 39.7107,
    "lon": -91.3581,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "Samuel Clemens' childhood home and surrounding museum properties connect real Hannibal people and places to The Adventures of Tom Sawyer.",
    "suggestedBook": "The Adventures of Tom Sawyer, selected chapters or adapted edition",
    "detourMiles": "55",
    "stopMinutes": "120",
    "visitStyle": "Multi-building literary history visit",
    "experience": "The boyhood home, museum galleries, family history, town streets, and the process of transforming childhood memories into fiction.",
    "why": "It lets her decide which parts of a famous adventure feel real and which feel exaggerated.",
    "quest": "Find three real details that an author could transform into an adventure scene.",
    "sisterCrossover": "Elsie can find the most mischievous story, while Emma looks at period clothing and town life.",
    "access": "This is a major branch from the primary route. Admission covers multiple properties, so allow a half day if selected.",
    "official": "https://marktwainmuseum.org/",
    "learnMore": "https://marktwainmuseum.org/boyhood-home/"
  },
  {
    "id": "K-012",
    "title": "Becky Thatcher House",
    "city": "Hannibal",
    "state": "MO",
    "lat": 39.7108,
    "lon": -91.3579,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "The home is associated with Laura Hawkins, Samuel Clemens' childhood friend and a model for Becky Thatcher.",
    "suggestedBook": "The Adventures of Tom Sawyer, Becky Thatcher chapters",
    "detourMiles": "55",
    "stopMinutes": "35",
    "visitStyle": "Character versus real-person comparison",
    "experience": "A real house connected to a fictional character and exhibits explaining the people behind Twain's stories.",
    "why": "It raises the interesting question of whether authors borrow, change, or unfairly define people they know.",
    "quest": "List two ways a real friend and a fictional character might be similar, and two ways they should remain different.",
    "sisterCrossover": "The sisters can each choose which fictional character most resembles someone in the family, without naming that person publicly.",
    "access": "Usually visited as part of the Mark Twain museum campus. Confirm the current building schedule.",
    "official": "https://marktwainmuseum.org/becky-thatcher-house/",
    "learnMore": "https://marktwainmuseum.org/"
  },
  {
    "id": "K-013",
    "title": "Mark Twain Cave",
    "city": "Hannibal",
    "state": "MO",
    "lat": 39.6886,
    "lon": -91.3319,
    "icon": "fashion",
    "interest": "Active Challenges",
    "storyConnection": "The cave is the real landscape behind some of the most suspenseful scenes in The Adventures of Tom Sawyer.",
    "suggestedBook": "The Adventures of Tom Sawyer, cave chapters",
    "detourMiles": "55",
    "stopMinutes": "75",
    "visitStyle": "Guided cave tour",
    "experience": "Narrow passages, geology, darkness, local history, and a setting where the real environment is more complex than a reader may imagine.",
    "why": "It combines movement, controlled fear, mystery, and a direct book setting.",
    "quest": "Before entering, draw what the cave scene looks like in her mind. Afterward, mark what the real cave changed.",
    "sisterCrossover": "Elsie gets the spooky setting, while Emma can study rock, temperature, and cave safety.",
    "access": "Guided ticketed tour. Expect stairs, uneven surfaces, cool temperatures, and confined spaces.",
    "official": "https://www.marktwaincave.com/",
    "learnMore": "https://www.marktwaincave.com/mark-twain-cave"
  },
  {
    "id": "K-014",
    "title": "The Novel Neighbor",
    "city": "Webster Groves",
    "state": "MO",
    "lat": 38.5884,
    "lon": -90.3516,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "A community bookstore known for children's and young-adult books, author events, and personalized recommendations.",
    "suggestedBook": "A staff-recommended middle-grade mystery",
    "detourMiles": "6",
    "stopMinutes": "45",
    "visitStyle": "Mystery recommendation challenge",
    "experience": "Curated shelves, local bookselling, recommendations, and the chance to compare her own choice with an expert's suggestion.",
    "why": "It reinforces that being a reader can be a social identity, not only a solitary activity.",
    "quest": "Give the bookseller three things she likes and three things she does not want. Let the bookseller choose the title.",
    "sisterCrossover": "Each sister supplies one recommendation condition, but Katrina has the final veto.",
    "access": "Check current store hours and event closures before detouring into Webster Groves.",
    "official": "https://thenovelneighbor.com/",
    "learnMore": "https://www.nobleneighbor.org/"
  },
  {
    "id": "K-015",
    "title": "St. Louis Public Library Central Library",
    "city": "St. Louis",
    "state": "MO",
    "lat": 38.6308,
    "lon": -90.2004,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "The grand restored library offers monumental halls, carved details, reading rooms, and an atmosphere suited to a puzzle or secret-society story.",
    "suggestedBook": "The Mysterious Benedict Society",
    "detourMiles": "1",
    "stopMinutes": "60",
    "visitStyle": "Architectural clue walk",
    "experience": "Beaux-Arts design, public reading spaces, stairways, art, and the contrast between a historic building and a modern library.",
    "why": "The building feels grown-up and mysterious while remaining a comfortable public space.",
    "quest": "Find a symbol, pattern, or object that could serve as the entrance code to a secret reading society.",
    "sisterCrossover": "Elsie chooses the most mysterious room, and Emma chooses the best-designed room.",
    "access": "Public areas are free. Architectural tours and room access can vary with programs and private events.",
    "official": "https://www.slpl.org/locations/central-library/",
    "learnMore": "https://www.slpl.org/central-library-tours/"
  },
  {
    "id": "K-016",
    "title": "City Museum",
    "city": "St. Louis",
    "state": "MO",
    "lat": 38.634,
    "lon": -90.2005,
    "icon": "fashion",
    "interest": "Active Challenges",
    "storyConnection": "A maze-like environment built from architectural salvage feels like an adventure setting that must be climbed, decoded, and navigated.",
    "suggestedBook": "The Mysterious Benedict Society",
    "detourMiles": "1",
    "stopMinutes": "180",
    "visitStyle": "Active family exploration",
    "experience": "Tunnels, slides, climbing structures, unexpected passages, rooftop elements, art, and repurposed objects.",
    "why": "It replaces karate with a broader test of courage, balance, judgment, and movement.",
    "quest": "Select one route through the museum and lead the family without retracing steps for ten minutes.",
    "sisterCrossover": "Elsie finds the strangest object, while Emma chooses the best photo location.",
    "access": "Wear secure athletic shoes and clothing suited for climbing. Adult supervision and meeting points are essential.",
    "official": "https://citymuseum.org/",
    "learnMore": "https://citymuseum.org/plan-your-visit/"
  },
  {
    "id": "K-017",
    "title": "Gateway Arch Museum and Tram",
    "city": "St. Louis",
    "state": "MO",
    "lat": 38.6247,
    "lon": -90.1848,
    "icon": "book",
    "interest": "Science & Weather",
    "storyConnection": "The Arch provides a nonfiction story about design competition, engineering, expansion, river geography, and the meaning people assign to monuments.",
    "suggestedBook": "Where Is the Gateway Arch?",
    "detourMiles": "0",
    "stopMinutes": "120",
    "visitStyle": "Museum plus tram ride",
    "experience": "A below-ground museum, the compact tram system, observation windows, river views, and a structure that changes appearance from every angle.",
    "why": "The tram ride feels adventurous, while the engineering story rewards her curiosity about how things work.",
    "quest": "Explain how the tram solves the problem of traveling inside a curved structure.",
    "sisterCrossover": "Emma studies design and weather visibility, while Elsie imagines a mystery inside the Arch.",
    "access": "Tram tickets are timed and the capsules are small. Security screening applies.",
    "official": "https://www.nps.gov/jeff/index.htm",
    "learnMore": "https://www.gatewayarch.com/"
  },
  {
    "id": "K-018",
    "title": "Abraham Lincoln Presidential Library and Museum",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.8034,
    "lon": -89.6474,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "The museum uses documents, objects, environments, and interpretation to build a biography of Lincoln and the country around him.",
    "suggestedBook": "Lincoln: A Photobiography",
    "detourMiles": "2",
    "stopMinutes": "120",
    "visitStyle": "Biography evidence challenge",
    "experience": "Immersive galleries, original-source material, political history, family stories, speeches, and questions about memory.",
    "why": "It asks her to evaluate how a museum turns a complicated person into a story.",
    "quest": "Choose one object that tells a stronger story than a paragraph of text, and explain why.",
    "sisterCrossover": "Emma looks at clothing and presentation, while Elsie finds the most emotionally intense gallery.",
    "access": "Ticketed museum. Some presentations may be intense for younger visitors, so preview current galleries.",
    "official": "https://presidentlincoln.illinois.gov/",
    "learnMore": "https://presidentlincoln.illinois.gov/visit/"
  },
  {
    "id": "K-019",
    "title": "Lincoln Home National Historic Site",
    "city": "Springfield",
    "state": "IL",
    "lat": 39.797,
    "lon": -89.6455,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "The preserved home and neighborhood show the ordinary rooms, routines, and family setting behind a famous public biography.",
    "suggestedBook": "Who Was Abraham Lincoln?",
    "detourMiles": "1",
    "stopMinutes": "75",
    "visitStyle": "Free timed house tour",
    "experience": "A historic neighborhood, domestic spaces, ranger interpretation, and the difference between public reputation and private life.",
    "why": "It makes a distant historical figure more understandable by placing him inside a family home.",
    "quest": "Choose one room and write what a child in the household might notice that an adult biography would ignore.",
    "sisterCrossover": "Emma studies the home's style, while Elsie searches for the room with the strongest atmosphere.",
    "access": "House tours are free but require same-day timed tickets. The neighborhood grounds have broader hours.",
    "official": "https://www.nps.gov/liho/index.htm",
    "learnMore": "https://www.nps.gov/liho/planyourvisit/guidedtours.htm"
  },
  {
    "id": "K-020",
    "title": "Old Joliet Prison",
    "city": "Joliet",
    "state": "IL",
    "lat": 41.5486,
    "lon": -88.074,
    "icon": "ghost",
    "interest": "Mystery & Unusual History",
    "storyConnection": "The historic prison allows Katrina to compare the reality of confinement, architecture, and institutional life with prisons portrayed in fiction.",
    "suggestedBook": "Al Capone Does My Shirts",
    "detourMiles": "2",
    "stopMinutes": "90",
    "visitStyle": "Historic guided or self-guided tour",
    "experience": "Cell houses, stone walls, prison operations, film history, and the practical design of a controlled institution.",
    "why": "It offers some of Elsie's eerie atmosphere while focusing on how a real place works.",
    "quest": "List three details a fiction writer might exaggerate and three details that are already dramatic enough.",
    "sisterCrossover": "Elsie handles the atmosphere, while Katrina becomes the fact-checker.",
    "access": "Seasonal ticketed site. Choose the historical tour, not a staged Halloween event.",
    "official": "https://www.jolietprison.org/tours.html",
    "learnMore": "https://www.jolietprison.org/"
  },
  {
    "id": "K-021",
    "title": "Plainfield Tornado Victim Memorial",
    "city": "Plainfield",
    "state": "IL",
    "lat": 41.6164,
    "lon": -88.2036,
    "icon": "book",
    "interest": "Science & Weather",
    "storyConnection": "The memorial anchors a respectful study of the August 28, 1990 F5 tornado and how warnings, radar, schools, and communities respond to severe weather.",
    "suggestedBook": "Night of the Twisters",
    "detourMiles": "10",
    "stopMinutes": "40",
    "visitStyle": "Memorial plus official track-map discussion",
    "experience": "A place of remembrance and a documented storm story that changed severe-weather communication.",
    "why": "It combines a survival narrative with the responsibility of separating fiction, memory, and official evidence.",
    "quest": "Identify one decision a character controls during a tornado and one danger no character can control.",
    "sisterCrossover": "Emma studies weather science, while Katrina studies choices within the story.",
    "access": "Visit quietly and respectfully. Do not treat the memorial or recovered neighborhoods as entertainment.",
    "official": "https://www.weather.gov/lot/1990_08_28_PlainfieldTornado",
    "learnMore": "https://www.plainfield-il.org/"
  },
  {
    "id": "K-022",
    "title": "Art Institute of Chicago, Thorne Miniature Rooms",
    "city": "Chicago",
    "state": "IL",
    "lat": 41.8796,
    "lon": -87.6237,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "The 68 miniature rooms are the direct setting and inspiration for The Sixty-Eight Rooms series.",
    "suggestedBook": "The Sixty-Eight Rooms",
    "detourMiles": "30",
    "stopMinutes": "120",
    "visitStyle": "Book-setting gallery visit",
    "experience": "Historically detailed rooms at miniature scale, period design, visual clues, and the exact museum objects transformed into a fantasy series.",
    "why": "This is a direct opportunity to step up to a place she has already visited in a book.",
    "quest": "Choose one room to enter. Write the problem she discovers there and the one object she can bring back.",
    "sisterCrossover": "Emma studies fashion and interiors, while Elsie chooses the room with the strongest mystery.",
    "access": "This is a substantial Chicago branch. Museum admission, traffic, parking, and gallery hours require advance planning.",
    "official": "https://www.artic.edu/highlights/12/thorne-miniature-rooms",
    "learnMore": "https://www.penguinrandomhouse.com/books/176556/the-sixty-eight-rooms-by-marianne-malone/"
  },
  {
    "id": "K-023",
    "title": "Frederick C. Robie House",
    "city": "Chicago",
    "state": "IL",
    "lat": 41.7898,
    "lon": -87.5951,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "Frank Lloyd Wright's Robie House is central to Blue Balliett's middle-grade mystery The Wright 3.",
    "suggestedBook": "The Wright 3",
    "detourMiles": "28",
    "stopMinutes": "90",
    "visitStyle": "Guided architecture tour",
    "experience": "Horizontal lines, art glass, hidden circulation, built-in design, and a real building treated as a mystery worth protecting.",
    "why": "The house rewards careful observation and makes architecture feel like a code.",
    "quest": "Find a repeated shape or line and explain what message it sends about the building.",
    "sisterCrossover": "Emma evaluates the design, Elsie looks for hidden spaces, and Katrina assembles the clues.",
    "access": "Ticketed tours have stairs and controlled timing. This should be paired with the Griffin Museum or Art Institute only on a planned Chicago day.",
    "official": "https://flwright.org/tour/robie-house",
    "learnMore": "https://flwright.org/sites/default/files/2023-07/The-Wright-3-Educator-Resource-Packet.pdf"
  },
  {
    "id": "K-024",
    "title": "Griffin Museum of Science and Industry, Science Storms",
    "city": "Chicago",
    "state": "IL",
    "lat": 41.7906,
    "lon": -87.5831,
    "icon": "book",
    "interest": "Science & Weather",
    "storyConnection": "The gallery's indoor tornado and other physical-force experiments can be used to test whether storm scenes in books behave realistically.",
    "suggestedBook": "The Boy Who Harnessed the Wind, Young Readers Edition",
    "detourMiles": "27",
    "stopMinutes": "150",
    "visitStyle": "Full interactive museum visit",
    "experience": "A large tornado vortex, lightning, waves, fire, sunlight, motion, and experiments that make invisible forces visible.",
    "why": "She can become the family's story fact-checker by testing what weather can really do.",
    "quest": "Choose one dramatic weather scene from a book and identify which museum evidence supports or contradicts it.",
    "sisterCrossover": "Emma leads the weather science, while Katrina translates it into story rules.",
    "access": "A major time commitment. Reserve admission and parking or transit, and do not combine with too many other Chicago stops.",
    "official": "https://www.griffinmsi.org/exhibits/science-storms",
    "learnMore": "https://www.griffinmsi.org/"
  },
  {
    "id": "K-025",
    "title": "Indiana Dunes Visitor Center and Diana of the Dunes Story",
    "city": "Porter",
    "state": "IN",
    "lat": 41.6331,
    "lon": -87.0544,
    "icon": "ghost",
    "interest": "Mystery & Unusual History",
    "storyConnection": "The visitor center provides the factual starting point for the story of Alice Mabel Gray, whose solitary life in the dunes became the legend of Diana of the Dunes.",
    "suggestedBook": "National Park Service Diana of the Dunes story",
    "detourMiles": "2",
    "stopMinutes": "75",
    "visitStyle": "Visitor center plus short dune walk",
    "experience": "Maps, ecosystems, shifting sand, conservation history, and a real person whose life became a regional legend.",
    "why": "It sits exactly between Elsie's folklore and Katrina's interest in what really happened.",
    "quest": "Make two columns titled Documented and Legend. Place each detail from the story into one column.",
    "sisterCrossover": "Elsie argues for the legend, Emma explains the ecosystem, and Katrina judges the evidence.",
    "access": "Confirm trail, parking, fee, and weather conditions. Stay on marked routes and leave before closing.",
    "official": "https://www.nps.gov/indu/planyourvisit/visitor-centers.htm",
    "learnMore": "https://www.nps.gov/thingstodo/dianadunesdare.htm"
  },
  {
    "id": "K-026",
    "title": "Old Lighthouse Museum",
    "city": "Michigan City",
    "state": "IN",
    "lat": 41.7218,
    "lon": -86.9055,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "A keeper's home and lighthouse provide a real setting for stories about storms, responsibility, isolation, and keeping a signal operating.",
    "suggestedBook": "The Lighthouse Family: The Storm",
    "detourMiles": "2",
    "stopMinutes": "60",
    "visitStyle": "Lighthouse museum and harbor walk",
    "experience": "Keeper rooms, lenses, harbor history, stairs, navigation, and the practical work required before automated lights.",
    "why": "The book may skew younger, but the real keeper challenge gives her a more mature way to share it with Emma.",
    "quest": "Create a four-step emergency checklist for a keeper during a storm.",
    "sisterCrossover": "Emma studies weather, Elsie considers the isolation, and Katrina runs the emergency plan.",
    "access": "Seasonal museum, generally with limited afternoon hours. Stairs and lack of an elevator may affect access.",
    "official": "https://michigancitylighthousemuseum.com/",
    "learnMore": "https://michigancitylighthousemuseum.com/about/"
  },
  {
    "id": "K-027",
    "title": "The History Museum, All-American Girls Professional Baseball League Collection",
    "city": "South Bend",
    "state": "IN",
    "lat": 41.674,
    "lon": -86.2599,
    "icon": "fashion",
    "interest": "Sports & Sister Crossover",
    "storyConnection": "The museum is the national repository for the All-American Girls Professional Baseball League Players Association, including uniforms, equipment, photographs, film, and records.",
    "suggestedBook": "A Strong Right Arm",
    "detourMiles": "1",
    "stopMinutes": "100",
    "visitStyle": "Women's sports story investigation",
    "experience": "Real athlete stories, uniforms, equipment, team history, film, and a large historic clothing collection.",
    "why": "It lets her connect physical skill and determination to stories about girls choosing who they wanted to become.",
    "quest": "Select one athlete and write the first paragraph of a sports novel based on her real challenge.",
    "sisterCrossover": "Emma studies the uniform, while Katrina tells the athlete's story.",
    "access": "Public exhibits rotate. Large portions of the clothing and archive collections are stored rather than displayed.",
    "official": "https://www.historymuseumsb.org/research-history/aagpbl/",
    "learnMore": "https://www.historymuseumsb.org/research-history/collections/"
  },
  {
    "id": "K-028",
    "title": "Hammes Notre Dame Bookstore and Stadium Story Stop",
    "city": "Notre Dame",
    "state": "IN",
    "lat": 41.6952,
    "lon": -86.2386,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "The bookstore provides sports biographies, university history, apparel, and the setting for Katrina to connect reading with the discipline behind college athletics.",
    "suggestedBook": "The Playbook",
    "detourMiles": "3",
    "stopMinutes": "60",
    "visitStyle": "Bookstore visit plus public stadium exterior walk",
    "experience": "Sports books, university identity, merchandise, campus storytelling, and views of a stadium built around tradition.",
    "why": "The stop keeps the useful parts of karate, discipline and effort, without requiring her to remain interested in karate itself.",
    "quest": "Find one athlete quote she believes and one that sounds impressive but is not actually useful.",
    "sisterCrossover": "Emma studies merchandise design, and Katrina evaluates the message behind it.",
    "access": "Bookstore and campus hours vary around events. Stadium interior access requires a separately scheduled tour or event.",
    "official": "https://hospitality.nd.edu/explore/shop-at-nd/",
    "learnMore": "https://tour.nd.edu/locations/notre-dame-stadium/"
  },
  {
    "id": "K-029",
    "title": "Kalamazoo Valley Museum, Tracing the Path",
    "city": "Kalamazoo",
    "state": "MI",
    "lat": 42.2917,
    "lon": -85.5844,
    "icon": "book",
    "interest": "Science & Weather",
    "storyConnection": "The museum's digital exhibit reconstructs the May 13, 1980 tornado through maps, video, interviews, newspapers, and eyewitness stories.",
    "suggestedBook": "I Survived the Joplin Tornado, 2011",
    "detourMiles": "1",
    "stopMinutes": "90",
    "visitStyle": "Museum plus digital tornado archive",
    "experience": "A documented storm path, personal accounts, media, scientific evidence, and the way a city remembers an event decades later.",
    "why": "It treats the storm as both science and narrative, allowing her to compare a fictional survivor with real witnesses.",
    "quest": "Select one eyewitness detail a novelist should include and one detail a novelist should not change.",
    "sisterCrossover": "Emma handles the weather facts, while Katrina evaluates how the story is told.",
    "access": "General admission is free. Open the digital exhibit before or during the visit because not every element is a permanent physical display.",
    "official": "https://kalamazoomuseum.org/exhibits/tracing-the-path-the-1980-kalamazoo-tornado",
    "learnMore": "https://kalamazoomuseum.org/"
  },
  {
    "id": "K-030",
    "title": "Kazoo Books",
    "city": "Kalamazoo",
    "state": "MI",
    "lat": 42.2687,
    "lon": -85.6152,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "An independent new, used, and rare bookstore where the search itself can become a hunt for an unexpected Michigan, mystery, or adventure title.",
    "suggestedBook": "A used mystery Katrina has never heard of",
    "detourMiles": "4",
    "stopMinutes": "50",
    "visitStyle": "Used-book treasure hunt",
    "experience": "Crowded shelves, older covers, local authors, unusual editions, and books that may no longer appear in chain stores.",
    "why": "A used bookstore feels less predictable and lets her discover rather than receive a planned recommendation.",
    "quest": "Find the oldest-looking middle-grade book she would still genuinely read. Explain what makes it appealing.",
    "sisterCrossover": "Elsie finds the strangest cover, Emma finds the best-designed cover, and Katrina chooses the winner.",
    "access": "Verify current hours. The store is typically closed Sundays.",
    "official": "https://www.kazoobooks.com/",
    "learnMore": "https://www.kazoobooks.com/about-us"
  },
  {
    "id": "K-031",
    "title": "Jeremiah Cronin House, inspiration for The House with a Clock in Its Walls",
    "city": "Marshall",
    "state": "MI",
    "lat": 42.2761,
    "lon": -84.9595,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "John Bellairs used this unusual Marshall house as inspiration for the home in The House with a Clock in Its Walls.",
    "suggestedBook": "The House with a Clock in Its Walls",
    "detourMiles": "3",
    "stopMinutes": "25",
    "visitStyle": "Respectful exterior architecture stop",
    "experience": "A real Victorian-era house whose towers, windows, shapes, and atmosphere became the basis for a middle-grade supernatural mystery.",
    "why": "It is the strongest bridge between her reading identity and Elsie's spooky interests.",
    "quest": "Find five exterior details Bellairs could turn into clues, hiding places, or false alarms.",
    "sisterCrossover": "Elsie supplies the haunting theory, while Katrina tests whether the house actually supports it.",
    "access": "Private property. View only from a legal public location, remain quiet, and do not enter the grounds.",
    "official": "https://choosemarshall.com/john-bellairs/",
    "learnMore": "https://www.penguinrandomhouse.com/books/11654/the-house-with-a-clock-in-its-walls-by-john-bellairs/"
  },
  {
    "id": "K-032",
    "title": "Honolulu House Museum",
    "city": "Marshall",
    "state": "MI",
    "lat": 42.2728,
    "lon": -84.959,
    "icon": "ghost",
    "interest": "Mystery & Unusual History",
    "storyConnection": "The unusual house and Marshall's architectural character help explain why John Bellairs repeatedly used the town as the emotional landscape for his mysteries.",
    "suggestedBook": "The Figure in the Shadows",
    "detourMiles": "3",
    "stopMinutes": "60",
    "visitStyle": "Historic house tour",
    "experience": "A distinctive house influenced by Hawaiian and Italianate design, period rooms, local history, and a town that already looks fictional.",
    "why": "The building is strange enough for Elsie, visually interesting enough for Emma, and rich enough in story logic for Katrina.",
    "quest": "Choose the feature a mystery writer would introduce in chapter one and explain when it becomes important later.",
    "sisterCrossover": "Each sister chooses a different genre for a story set in the house.",
    "access": "Seasonal museum with limited weekly hours. Confirm the current tour schedule.",
    "official": "https://www.marshallmich.net/honolulu-house",
    "learnMore": "https://choosemarshall.com/john-bellairs/"
  },
  {
    "id": "K-033",
    "title": "Curious Book Shop",
    "city": "East Lansing",
    "state": "MI",
    "lat": 42.734,
    "lon": -84.4775,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "Three floors of used and rare books create a more grown-up book-hunting experience close to Michigan State University.",
    "suggestedBook": "A classic mystery in an older edition",
    "detourMiles": "3",
    "stopMinutes": "55",
    "visitStyle": "Three-floor book quest",
    "experience": "Dense shelves, older editions, genre sections, covers from different decades, and the feeling of discovering something overlooked.",
    "why": "It gives her a mature reader's stop without requiring a specific academic interest.",
    "quest": "Find two editions of the same book and decide which one she would buy based on cover, size, age, and condition.",
    "sisterCrossover": "Emma judges the cover, Elsie judges the atmosphere, and Katrina makes the final purchase argument.",
    "access": "Aisles and stairs can be tight. Verify current hours and supervise browsing.",
    "official": "https://curiousbooks.com/",
    "learnMore": "https://curiousbooks.com/about-us/"
  },
  {
    "id": "K-034",
    "title": "Curwood Castle",
    "city": "Owosso",
    "state": "MI",
    "lat": 42.9978,
    "lon": -84.177,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "Author James Oliver Curwood built the small castle as a writing studio, connecting adventure writing, animal stories, architecture, and conservation.",
    "suggestedBook": "Selected James Oliver Curwood animal story, parent preview",
    "detourMiles": "25",
    "stopMinutes": "60",
    "visitStyle": "Author studio museum",
    "experience": "A writer's personal workspace, castle-like design, historic objects, and the life of an author whose views on wildlife changed over time.",
    "why": "The stop makes writing feel physical by showing where an author chose to work and what he placed around himself.",
    "quest": "Design her ideal writing room using only five objects and explain the purpose of each.",
    "sisterCrossover": "Elsie can make the room mysterious, Emma can style it, and Katrina decides what helps the story.",
    "access": "Optional branch with seasonal afternoon hours. Verify before detouring from Lansing.",
    "official": "https://www.owossomuseum.com/curwood-castle/",
    "learnMore": "https://www.michigan.org/property/curwood-castle"
  },
  {
    "id": "K-035",
    "title": "Otsego County Library",
    "city": "Gaylord",
    "state": "MI",
    "lat": 45.0215,
    "lon": -84.6747,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "The library offers teen and children's services, local material, and a practical place to choose the final book or activity before reaching the Straits.",
    "suggestedBook": "Choose one northern Michigan or island story",
    "detourMiles": "0",
    "stopMinutes": "40",
    "visitStyle": "Local-reading and makerspace stop",
    "experience": "A community library, regional information, recommendations, and programs serving a northern Michigan town.",
    "why": "It gives her ownership of the final portion of the route and a calm break after long driving.",
    "quest": "Find one nonfiction book that answers a question she has about the island or Great Lakes.",
    "sisterCrossover": "Each sister asks one question, and Katrina chooses which question the family researches.",
    "access": "Check daily hours and program schedules. Library cards may be required for borrowing, but public reading is available.",
    "official": "https://www.otsegocountylibrary.org/",
    "learnMore": "https://www.otsegocountylibrary.org/main-branch"
  },
  {
    "id": "K-036",
    "title": "Chillermania",
    "city": "Indian River",
    "state": "MI",
    "lat": 45.4052,
    "lon": -84.6217,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "The bookstore and headquarters of author Johnathan Rand is dedicated to children's adventure and mystery books, including the Michigan Chillers series.",
    "suggestedBook": "Mayhem on Mackinac Island",
    "detourMiles": "2",
    "stopMinutes": "60",
    "visitStyle": "Michigan mystery headquarters",
    "experience": "A store built around a children's author, regional settings, series branding, covers, merchandise, and the possibility of choosing a story tied to the next destination.",
    "why": "This may be her ideal stop because it combines reading, age-appropriate suspense, local geography, and Elsie's spooky influence.",
    "quest": "Choose a Michigan Chillers location and predict the ordinary place that will become dangerous in the story.",
    "sisterCrossover": "Elsie chooses the scariest title, Emma chooses the best cover, and Katrina selects the book.",
    "access": "Seasonal and event hours can vary. Confirm the store schedule before the northern Michigan drive.",
    "official": "https://www.michigan.org/property/chillermania",
    "learnMore": "https://chillermania.com/collections/michigan-chillers"
  },
  {
    "id": "K-037",
    "title": "The Island Bookstore",
    "city": "Mackinac Island",
    "state": "MI",
    "lat": 45.8495,
    "lon": -84.6186,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "A seasonal island bookstore specializing in regional authors, Mackinac history, nature, and children's stories.",
    "suggestedBook": "Katrina chooses one Mackinac or Great Lakes title",
    "detourMiles": "0",
    "stopMinutes": "45",
    "visitStyle": "Local-book selection during a separate island visit",
    "experience": "Books selected for the place she is visiting, local authors, island history, and the contrast between a seasonal bookstore and a mainland store.",
    "why": "She can test whether a book feels more meaningful when purchased in the place it describes.",
    "quest": "Select one local book and find a real location that could appear on its cover.",
    "sisterCrossover": "All three sisters choose one island book, but Katrina ranks which is most specific to the place.",
    "access": "This requires a separate passenger ferry. The bookstore is seasonal, generally May through October.",
    "official": "https://www.islandbookstore.com/",
    "learnMore": "https://www.mackinacisland.org/businesses/island-bookstore/"
  },
  {
    "id": "K-038",
    "title": "Fort Mackinac",
    "city": "Mackinac Island",
    "state": "MI",
    "lat": 45.8526,
    "lon": -84.6178,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "The restored fort and children's quarters connect directly to A Boy at Fort Mackinac and stories about daily life, military routines, and island history.",
    "suggestedBook": "A Boy at Fort Mackinac",
    "detourMiles": "0",
    "stopMinutes": "120",
    "visitStyle": "Historic fort and book-setting visit",
    "experience": "Historic buildings, interpreters, demonstrations, views, children's activities, and the physical spaces described in an island history story.",
    "why": "The fort makes nonfiction active and gives her a real place to test a character's choices.",
    "quest": "Choose one fort job she could perform for a day and one she would refuse. Explain both choices.",
    "sisterCrossover": "Emma studies uniforms, Elsie finds the fort legend, and Katrina writes the day-in-the-life scene.",
    "access": "Seasonal ticketed site reached by ferry, walking, bicycle, or carriage. The uphill approach can be strenuous.",
    "official": "https://www.mackinacparks.com/attraction/fort-mackinac/",
    "learnMore": "https://www.mackinacparks.com/product/a-boy-at-fort-mackinac/"
  },
  {
    "id": "K-039",
    "title": "Bois Blanc Island Historical Society Museum and Library",
    "city": "Bois Blanc Island",
    "state": "MI",
    "lat": 45.7488,
    "lon": -84.4955,
    "icon": "book",
    "interest": "Books & Story Places",
    "storyConnection": "The small island museum and library preserve photographs, community records, school stories, transportation history, and the details of daily island life.",
    "suggestedBook": "A local history selection or museum photograph story",
    "detourMiles": "0",
    "stopMinutes": "60",
    "visitStyle": "Island history and photograph investigation",
    "experience": "A small-community collection where ordinary families, ferries, schools, weather, work, and recreation become the island's story.",
    "why": "She can discover a story that neither sister found online before the trip.",
    "quest": "Choose one historical photograph and write the questions she would ask the person in it.",
    "sisterCrossover": "Each sister finds one detail connected to her own theme, but Katrina combines the three into one story.",
    "access": "Very limited seasonal hours. Confirm directly with the township or historical society before relying on the stop.",
    "official": "https://www.boisblanctownship.org/community/museum-and-library/",
    "learnMore": "https://www.boisblanctownship.org/"
  },
  {
    "id": "K-040",
    "title": "Bois Blanc Family Bike Ride and Story Quest Finish",
    "city": "Bois Blanc Island",
    "state": "MI",
    "lat": 45.7465,
    "lon": -84.496,
    "icon": "fashion",
    "interest": "Active Challenges",
    "storyConnection": "The island's public gravel roads and community bike-ride concept create a moving final chapter in which Katrina becomes the route leader and storyteller.",
    "suggestedBook": "The Wild Robot",
    "detourMiles": "0",
    "stopMinutes": "120",
    "visitStyle": "Family bike loop or shorter active quest",
    "experience": "Unpaved island roads, changing weather, navigation, natural areas, ferry timing, and the practical challenge of completing an island route.",
    "why": "It gives her independence, physical challenge, and the authority to decide how the family's story ends.",
    "quest": "Lead a safe route, choose three chapter locations, and narrate the final chapter aloud at the last stop.",
    "sisterCrossover": "Elsie contributes the mystery, Emma contributes the visual or weather detail, and Katrina controls the plot.",
    "access": "Roads are largely unpaved. Check bicycles, weather, insects, daylight, ferry schedule, public access, food, and water. Shorter family routes may be better than the full 19-mile community ride.",
    "official": "https://www.boisblanctownship.org/",
    "learnMore": "https://www.michigan.gov/dnr/places/natural-areas/bois-blanc-island"
  }
];
